<?php

// Composer: "fzaninotto/faker": "v1.3.0"
use Faker\Factory as Faker;

class AreacodesTableSeeder extends Seeder {

	public function run()
	{

        Areacodes::create(array('area_code' => '0113', 'area_covered' => 'Leeds', 'official_Ofcom' => 'Leeds', 'Previous_BT' => 'Leeds'));
		Areacodes::create(array('area_code' => '0114', 'area_covered' => 'Sheffield', 'official_Ofcom' => 'Sheffield', 'Previous_BT' => 'Sheffield'));
		Areacodes::create(array('area_code' => '0115', 'area_covered' => 'Nottingham', 'official_Ofcom' => 'Nottingham', 'Previous_BT' => 'Nottingham'));
		Areacodes::create(array('area_code' => '0116', 'area_covered' => 'Leicester', 'official_Ofcom' => 'Leicester', 'Previous_BT' => 'Leicester'));
		Areacodes::create(array('area_code' => '0117', 'area_covered' => 'Bristol', 'official_Ofcom' => 'Bristol', 'Previous_BT' => 'Bristol Inner'));
		Areacodes::create(array('area_code' => '0118', 'area_covered' => 'Reading', 'official_Ofcom' => 'Reading', 'Previous_BT' => 'Reading'));
		Areacodes::create(array('area_code' => '01200', 'area_covered' => 'Clitheroe', 'official_Ofcom' => 'Clitheroe', 'Previous_BT' => 'Clitheroe'));
		Areacodes::create(array('area_code' => '01202', 'area_covered' => 'Bournemouth', 'official_Ofcom' => 'Bournemouth', 'Previous_BT' => 'Bournemouth'));
		Areacodes::create(array('area_code' => '01204', 'area_covered' => 'Bolton', 'official_Ofcom' => 'Bolton', 'Previous_BT' => 'Bolton'));
		Areacodes::create(array('area_code' => '01205', 'area_covered' => 'Boston', 'official_Ofcom' => 'Boston', 'Previous_BT' => 'Boston'));
		Areacodes::create(array('area_code' => '01206', 'area_covered' => 'Colchester', 'official_Ofcom' => 'Colchester', 'Previous_BT' => 'Colchester'));
		Areacodes::create(array('area_code' => '01207', 'area_covered' => 'Consett', 'official_Ofcom' => 'Consett', 'Previous_BT' => 'Consett'));
		Areacodes::create(array('area_code' => '01208', 'area_covered' => 'Bodmin', 'official_Ofcom' => 'Bodmin', 'Previous_BT' => 'Bodmin'));
		Areacodes::create(array('area_code' => '01209', 'area_covered' => 'Redruth', 'official_Ofcom' => 'Redruth', 'Previous_BT' => 'Redruth'));
		Areacodes::create(array('area_code' => '0121', 'area_covered' => 'Birmingham', 'official_Ofcom' => 'Birmingham', 'Previous_BT' => 'Birmingham'));
		Areacodes::create(array('area_code' => '01223', 'area_covered' => 'Cambridge', 'official_Ofcom' => 'Cambridge', 'Previous_BT' => 'Cambridge'));
		Areacodes::create(array('area_code' => '01224', 'area_covered' => 'Aberdeen', 'official_Ofcom' => 'Aberdeen', 'Previous_BT' => 'Aberdeen'));
		Areacodes::create(array('area_code' => '01225', 'area_covered' => 'Bath', 'official_Ofcom' => 'Bath', 'Previous_BT' => 'Bath'));
		Areacodes::create(array('area_code' => '01226', 'area_covered' => 'Barnsley', 'official_Ofcom' => 'Barnsley', 'Previous_BT' => 'Barnsley'));
		Areacodes::create(array('area_code' => '01227', 'area_covered' => 'Canterbury', 'official_Ofcom' => 'Canterbury', 'Previous_BT' => 'Canterbury'));
		Areacodes::create(array('area_code' => '01228', 'area_covered' => 'Carlisle', 'official_Ofcom' => 'Carlisle', 'Previous_BT' => 'Carlisle'));
		Areacodes::create(array('area_code' => '01229', 'area_covered' => 'Barrow-in Furness / Millom', 'official_Ofcom' => 'Barrow-in Furness / Millom', 'Previous_BT' => 'Barrow-in Furness / Millom'));
		Areacodes::create(array('area_code' => '01233', 'area_covered' => 'Ashford (Kent)', 'official_Ofcom' => 'Ashford (Kent)', 'Previous_BT' => 'Ashford (Kent)'));
		Areacodes::create(array('area_code' => '01234', 'area_covered' => 'Bedford', 'official_Ofcom' => 'Bedford', 'Previous_BT' => 'Bedford'));
		Areacodes::create(array('area_code' => '01235', 'area_covered' => 'Abingdon', 'official_Ofcom' => 'Abingdon', 'Previous_BT' => 'Abingdon'));
		Areacodes::create(array('area_code' => '01236', 'area_covered' => 'Coatbridge', 'official_Ofcom' => 'Coatbridge', 'Previous_BT' => 'Coatbridge'));
		Areacodes::create(array('area_code' => '01237', 'area_covered' => 'Bideford', 'official_Ofcom' => 'Bideford', 'Previous_BT' => 'Bideford'));
		Areacodes::create(array('area_code' => '01239', 'area_covered' => 'Cardigan', 'official_Ofcom' => 'Cardigan', 'Previous_BT' => 'Cardigan'));
		Areacodes::create(array('area_code' => '01241', 'area_covered' => 'Arbroath', 'official_Ofcom' => 'Arbroath', 'Previous_BT' => 'Arbroath'));
		Areacodes::create(array('area_code' => '01242', 'area_covered' => 'Cheltenham', 'official_Ofcom' => 'Cheltenham', 'Previous_BT' => 'Cheltenham'));
		Areacodes::create(array('area_code' => '01243', 'area_covered' => 'Chichester', 'official_Ofcom' => 'Chichester', 'Previous_BT' => 'Chichester'));
		Areacodes::create(array('area_code' => '01244', 'area_covered' => 'Chester', 'official_Ofcom' => 'Chester', 'Previous_BT' => 'Chester'));
		Areacodes::create(array('area_code' => '01245', 'area_covered' => 'Chelmsford', 'official_Ofcom' => 'Chelmsford', 'Previous_BT' => 'Chelmsford'));
		Areacodes::create(array('area_code' => '01246', 'area_covered' => 'Chesterfield', 'official_Ofcom' => 'Chesterfield', 'Previous_BT' => 'Chesterfield'));
		Areacodes::create(array('area_code' => '01248', 'area_covered' => 'Bangor (Gwynedd)', 'official_Ofcom' => 'Bangor (Gwynedd)', 'Previous_BT' => 'Bangor (Gwynedd)'));
		Areacodes::create(array('area_code' => '01249', 'area_covered' => 'Chippenham', 'official_Ofcom' => 'Chippenham', 'Previous_BT' => 'Chippenham'));
		Areacodes::create(array('area_code' => '01250', 'area_covered' => 'Blairgowrie', 'official_Ofcom' => 'Blairgowrie', 'Previous_BT' => 'Blairgowrie'));
		Areacodes::create(array('area_code' => '01252', 'area_covered' => 'Aldershot', 'official_Ofcom' => 'Aldershot', 'Previous_BT' => 'Aldershot'));
		Areacodes::create(array('area_code' => '01253', 'area_covered' => 'Blackpool', 'official_Ofcom' => 'Blackpool', 'Previous_BT' => 'Blackpool'));
		Areacodes::create(array('area_code' => '01254', 'area_covered' => 'Blackburn', 'official_Ofcom' => 'Blackburn', 'Previous_BT' => 'Blackburn'));
		Areacodes::create(array('area_code' => '01255', 'area_covered' => 'Clacton-on-Sea', 'official_Ofcom' => 'Clacton-on-Sea', 'Previous_BT' => 'Clacton-on-Sea'));
		Areacodes::create(array('area_code' => '01256', 'area_covered' => 'Basingstoke', 'official_Ofcom' => 'Basingstoke', 'Previous_BT' => 'Basingstoke'));
		Areacodes::create(array('area_code' => '01257', 'area_covered' => 'Coppull', 'official_Ofcom' => 'Coppull', 'Previous_BT' => 'Coppull'));
		Areacodes::create(array('area_code' => '01258', 'area_covered' => 'Blandford', 'official_Ofcom' => 'Blandford', 'Previous_BT' => 'Blandford'));
		Areacodes::create(array('area_code' => '01259', 'area_covered' => 'Alloa', 'official_Ofcom' => 'Alloa', 'Previous_BT' => 'Alloa'));
		Areacodes::create(array('area_code' => '01260', 'area_covered' => 'Congleton', 'official_Ofcom' => 'Congleton', 'Previous_BT' => 'Congleton (see also 01477)'));
		Areacodes::create(array('area_code' => '01261', 'area_covered' => 'Banff', 'official_Ofcom' => 'Banff', 'Previous_BT' => 'Banff'));
		Areacodes::create(array('area_code' => '01262', 'area_covered' => 'Bridlington', 'official_Ofcom' => 'Bridlington', 'Previous_BT' => 'Bridlington'));
		Areacodes::create(array('area_code' => '01263', 'area_covered' => 'Cromer', 'official_Ofcom' => 'Cromer', 'Previous_BT' => 'Cromer'));
		Areacodes::create(array('area_code' => '01264', 'area_covered' => 'Andover', 'official_Ofcom' => 'Andover', 'Previous_BT' => 'Andover'));
		Areacodes::create(array('area_code' => '01267', 'area_covered' => 'Carmarthen', 'official_Ofcom' => 'Carmarthen', 'Previous_BT' => 'Carmarthen'));
		Areacodes::create(array('area_code' => '01268', 'area_covered' => 'Basildon', 'official_Ofcom' => 'Basildon', 'Previous_BT' => 'Stanford-le-Hope (see also 01375)'));
		Areacodes::create(array('area_code' => '01269', 'area_covered' => 'Ammanford', 'official_Ofcom' => 'Ammanford', 'Previous_BT' => 'Ammanford'));
		Areacodes::create(array('area_code' => '01270', 'area_covered' => 'Crewe', 'official_Ofcom' => 'Crewe', 'Previous_BT' => 'Crewe'));
		Areacodes::create(array('area_code' => '01271', 'area_covered' => 'Barnstaple', 'official_Ofcom' => 'Barnstaple', 'Previous_BT' => 'Barnstaple'));
		Areacodes::create(array('area_code' => '01273', 'area_covered' => 'Brighton', 'official_Ofcom' => 'Brighton', 'Previous_BT' => 'Brighton'));
		Areacodes::create(array('area_code' => '01274', 'area_covered' => 'Bradford', 'official_Ofcom' => 'Bradford', 'Previous_BT' => 'Bradford'));
		Areacodes::create(array('area_code' => '01275', 'area_covered' => 'Clevedon', 'official_Ofcom' => 'Clevedon', 'Previous_BT' => 'Bristol Outer'));
		Areacodes::create(array('area_code' => '01276', 'area_covered' => 'Camberley', 'official_Ofcom' => 'Camberley', 'Previous_BT' => 'Ascot (see also 01344)'));
		Areacodes::create(array('area_code' => '01277', 'area_covered' => 'Brentwood', 'official_Ofcom' => 'Brentwood', 'Previous_BT' => 'Brentwood'));
		Areacodes::create(array('area_code' => '01278', 'area_covered' => 'Bridgwater', 'official_Ofcom' => 'Bridgwater', 'Previous_BT' => 'Bridgwater'));
		Areacodes::create(array('area_code' => '01279', 'area_covered' => 'Bishops Stortford', 'official_Ofcom' => 'Bishops Stortford', 'Previous_BT' => 'Bishops Stortford'));
		Areacodes::create(array('area_code' => '01280', 'area_covered' => 'Buckingham', 'official_Ofcom' => 'Buckingham', 'Previous_BT' => 'Buckingham'));
		Areacodes::create(array('area_code' => '01282', 'area_covered' => 'Burnley', 'official_Ofcom' => 'Burnley', 'Previous_BT' => 'Burnley'));
		Areacodes::create(array('area_code' => '01283', 'area_covered' => 'Burton-on-Trent', 'official_Ofcom' => 'Burton-on-Trent', 'Previous_BT' => 'Burton-on-Trent'));
		Areacodes::create(array('area_code' => '01284', 'area_covered' => 'Bury-St-Edmunds', 'official_Ofcom' => 'Bury-St-Edmunds', 'Previous_BT' => 'Bury-St-Edmunds'));
		Areacodes::create(array('area_code' => '01285', 'area_covered' => 'Cirencester', 'official_Ofcom' => 'Cirencester', 'Previous_BT' => 'Cirencester'));
		Areacodes::create(array('area_code' => '01286', 'area_covered' => 'Caernarfon', 'official_Ofcom' => 'Caernarfon', 'Previous_BT' => 'Caernarvon'));
		Areacodes::create(array('area_code' => '01287', 'area_covered' => 'Guisborough', 'official_Ofcom' => 'Guisborough', 'Previous_BT' => 'Guisborough'));
		Areacodes::create(array('area_code' => '01288', 'area_covered' => 'Bude', 'official_Ofcom' => 'Bude', 'Previous_BT' => 'Bude'));
		Areacodes::create(array('area_code' => '01289', 'area_covered' => 'Berwick-on-Tweed', 'official_Ofcom' => 'Berwick-on-Tweed', 'Previous_BT' => 'Berwick-on-Tweed'));
		Areacodes::create(array('area_code' => '01290', 'area_covered' => 'Cumnock', 'official_Ofcom' => 'Cumnock', 'Previous_BT' => 'Cumnock'));
		Areacodes::create(array('area_code' => '01291', 'area_covered' => 'Chepstow', 'official_Ofcom' => 'Chepstow', 'Previous_BT' => 'Shirenewton'));
		Areacodes::create(array('area_code' => '01292', 'area_covered' => 'Ayr', 'official_Ofcom' => 'Ayr', 'Previous_BT' => 'Ayr'));
		Areacodes::create(array('area_code' => '01293', 'area_covered' => 'Crawley', 'official_Ofcom' => 'Crawley', 'Previous_BT' => 'Newdigate (see also 01306)'));
		Areacodes::create(array('area_code' => '01294', 'area_covered' => 'Ardrossan', 'official_Ofcom' => 'Ardrossan', 'Previous_BT' => 'Ardrossan'));
		Areacodes::create(array('area_code' => '01295', 'area_covered' => 'Banbury', 'official_Ofcom' => 'Banbury', 'Previous_BT' => 'Banbury'));
		Areacodes::create(array('area_code' => '01296', 'area_covered' => 'Aylesbury', 'official_Ofcom' => 'Aylesbury', 'Previous_BT' => 'Aylesbury'));
		Areacodes::create(array('area_code' => '01297', 'area_covered' => 'Axminster', 'official_Ofcom' => 'Axminster', 'Previous_BT' => 'Axminster'));
		Areacodes::create(array('area_code' => '01298', 'area_covered' => 'Buxton', 'official_Ofcom' => 'Buxton', 'Previous_BT' => 'Buxton'));
		Areacodes::create(array('area_code' => '01299', 'area_covered' => 'Bewdley', 'official_Ofcom' => 'Bewdley', 'Previous_BT' => 'Bewdley'));
		Areacodes::create(array('area_code' => '01300', 'area_covered' => 'Cerne Abbas', 'official_Ofcom' => 'Cerne Abbas', 'Previous_BT' => 'Cerne Abbas'));
		Areacodes::create(array('area_code' => '01301', 'area_covered' => 'Arrochar', 'official_Ofcom' => 'Arrochar', 'Previous_BT' => 'Arrochar'));
		Areacodes::create(array('area_code' => '01302', 'area_covered' => 'Doncaster', 'official_Ofcom' => 'Doncaster', 'Previous_BT' => 'Doncaster'));
		Areacodes::create(array('area_code' => '01303', 'area_covered' => 'Folkestone', 'official_Ofcom' => 'Folkestone', 'Previous_BT' => 'Folkestone'));
		Areacodes::create(array('area_code' => '01304', 'area_covered' => 'Dover', 'official_Ofcom' => 'Dover', 'Previous_BT' => 'Dover'));
		Areacodes::create(array('area_code' => '01305', 'area_covered' => 'Dorchester', 'official_Ofcom' => 'Dorchester', 'Previous_BT' => 'Dorchester'));
		Areacodes::create(array('area_code' => '01306', 'area_covered' => 'Dorking', 'official_Ofcom' => 'Dorking', 'Previous_BT' => 'Newdigate (see also 01293)'));
		Areacodes::create(array('area_code' => '01307', 'area_covered' => 'Forfar', 'official_Ofcom' => 'Forfar', 'Previous_BT' => 'Forfar'));
		Areacodes::create(array('area_code' => '01308', 'area_covered' => 'Bridport', 'official_Ofcom' => 'Bridport', 'Previous_BT' => 'Bridport'));
		Areacodes::create(array('area_code' => '01309', 'area_covered' => 'Forres', 'official_Ofcom' => 'Forres', 'Previous_BT' => 'Forres'));
		Areacodes::create(array('area_code' => '0131', 'area_covered' => 'Edinburgh', 'official_Ofcom' => 'Edinburgh', 'Previous_BT' => 'Edinburgh'));
		Areacodes::create(array('area_code' => '01320', 'area_covered' => 'Fort Augustus', 'official_Ofcom' => 'Fort Augustus', 'Previous_BT' => 'Fort Augustus'));
		Areacodes::create(array('area_code' => '01322', 'area_covered' => 'Dartford', 'official_Ofcom' => 'Dartford', 'Previous_BT' => 'Swanley (see also 01689 and 01959)'));
		Areacodes::create(array('area_code' => '01323', 'area_covered' => 'Eastbourne', 'official_Ofcom' => 'Eastbourne', 'Previous_BT' => 'Eastbourne'));
		Areacodes::create(array('area_code' => '01324', 'area_covered' => 'Falkirk', 'official_Ofcom' => 'Falkirk', 'Previous_BT' => 'Falkirk'));
		Areacodes::create(array('area_code' => '01325', 'area_covered' => 'Darlington', 'official_Ofcom' => 'Darlington', 'Previous_BT' => 'Darlington'));
		Areacodes::create(array('area_code' => '01326', 'area_covered' => 'Falmouth', 'official_Ofcom' => 'Falmouth', 'Previous_BT' => 'Falmouth'));
		Areacodes::create(array('area_code' => '01327', 'area_covered' => 'Daventry', 'official_Ofcom' => 'Daventry', 'Previous_BT' => 'Weedon'));
		Areacodes::create(array('area_code' => '01328', 'area_covered' => 'Fakenham', 'official_Ofcom' => 'Fakenham', 'Previous_BT' => 'Fakenham'));
		Areacodes::create(array('area_code' => '01329', 'area_covered' => 'Fareham', 'official_Ofcom' => 'Fareham', 'Previous_BT' => 'Fareham (see also 01489)'));
		Areacodes::create(array('area_code' => '01330', 'area_covered' => 'Banchory', 'official_Ofcom' => 'Banchory', 'Previous_BT' => 'Banchory'));
		Areacodes::create(array('area_code' => '01332', 'area_covered' => 'Derby', 'official_Ofcom' => 'Derby', 'Previous_BT' => 'Derby'));
		Areacodes::create(array('area_code' => '01333', 'area_covered' => 'Anstruther', 'official_Ofcom' => 'Peat Inn', 'Previous_BT' => 'Peat Inn (see also 01334)'));
		Areacodes::create(array('area_code' => '01334', 'area_covered' => 'St Andrews', 'official_Ofcom' => 'St Andrews', 'Previous_BT' => 'Peat Inn (see also 01333)'));
		Areacodes::create(array('area_code' => '01335', 'area_covered' => 'Ashbourne', 'official_Ofcom' => 'Ashbourne', 'Previous_BT' => 'Ashbourne'));
		Areacodes::create(array('area_code' => '01337', 'area_covered' => 'Ladybank', 'official_Ofcom' => 'Ladybank', 'Previous_BT' => 'Ladybank'));
		Areacodes::create(array('area_code' => '01339', 'area_covered' => 'Aboyne / Ballater', 'official_Ofcom' => 'Aboyne / Ballater', 'Previous_BT' => 'Aboyne / Ballater'));
		Areacodes::create(array('area_code' => '01340', 'area_covered' => 'Craigellachie', 'official_Ofcom' => 'Craigellachie', 'Previous_BT' => 'Craigellachie'));
		Areacodes::create(array('area_code' => '01341', 'area_covered' => 'Barmouth', 'official_Ofcom' => 'Barmouth', 'Previous_BT' => 'Barmouth'));
		Areacodes::create(array('area_code' => '01342', 'area_covered' => 'East Grinstead', 'official_Ofcom' => 'East Grinstead', 'Previous_BT' => 'East Grinstead'));
		Areacodes::create(array('area_code' => '01343', 'area_covered' => 'Elgin', 'official_Ofcom' => 'Elgin', 'Previous_BT' => 'Elgin'));
		Areacodes::create(array('area_code' => '01344', 'area_covered' => 'Bracknell', 'official_Ofcom' => 'Bracknell', 'Previous_BT' => 'Ascot (see also 01276)'));
		Areacodes::create(array('area_code' => '01346', 'area_covered' => 'Fraserburgh', 'official_Ofcom' => 'Fraserburgh', 'Previous_BT' => 'Fraserburgh'));
		Areacodes::create(array('area_code' => '01347', 'area_covered' => 'Easingwold', 'official_Ofcom' => 'Easingwold', 'Previous_BT' => 'Easingwold'));
		Areacodes::create(array('area_code' => '01348', 'area_covered' => 'Fishguard', 'official_Ofcom' => 'Fishguard', 'Previous_BT' => 'Fishguard'));
		Areacodes::create(array('area_code' => '01349', 'area_covered' => 'Dingwall', 'official_Ofcom' => 'Dingwall', 'Previous_BT' => 'Dingwall'));
		Areacodes::create(array('area_code' => '01350', 'area_covered' => 'Dunkeld', 'official_Ofcom' => 'Dunkeld', 'Previous_BT' => 'Dunkeld'));
		Areacodes::create(array('area_code' => '01352', 'area_covered' => 'Mold', 'official_Ofcom' => 'Mold', 'Previous_BT' => 'Mold'));
		Areacodes::create(array('area_code' => '01353', 'area_covered' => 'Ely', 'official_Ofcom' => 'Ely', 'Previous_BT' => 'Ely'));
		Areacodes::create(array('area_code' => '01354', 'area_covered' => 'Chatteris', 'official_Ofcom' => 'Chatteris', 'Previous_BT' => 'Doddington'));
		Areacodes::create(array('area_code' => '01355', 'area_covered' => 'East Kilbride', 'official_Ofcom' => 'East Kilbride', 'Previous_BT' => 'East Kilbride (see also 01357)'));
		Areacodes::create(array('area_code' => '01356', 'area_covered' => 'Brechin', 'official_Ofcom' => 'Brechin', 'Previous_BT' => 'Brechin'));
		Areacodes::create(array('area_code' => '01357', 'area_covered' => 'Strathaven', 'official_Ofcom' => 'Strathaven', 'Previous_BT' => 'East Kilbride (see also 01355)'));
		Areacodes::create(array('area_code' => '01358', 'area_covered' => 'Ellon', 'official_Ofcom' => 'Ellon', 'Previous_BT' => 'Ellon'));
		Areacodes::create(array('area_code' => '01359', 'area_covered' => 'Pakenham', 'official_Ofcom' => 'Pakenham', 'Previous_BT' => 'Pakenham'));
		Areacodes::create(array('area_code' => '01360', 'area_covered' => 'Killearn', 'official_Ofcom' => 'Killearn', 'Previous_BT' => 'Killearn'));
		Areacodes::create(array('area_code' => '01361', 'area_covered' => 'Duns', 'official_Ofcom' => 'Duns', 'Previous_BT' => 'Duns'));
		Areacodes::create(array('area_code' => '01362', 'area_covered' => 'Dereham', 'official_Ofcom' => 'Dereham', 'Previous_BT' => 'Dereham'));
		Areacodes::create(array('area_code' => '01363', 'area_covered' => 'Crediton', 'official_Ofcom' => 'Crediton', 'Previous_BT' => 'Crediton'));
		Areacodes::create(array('area_code' => '01364', 'area_covered' => 'Ashburton', 'official_Ofcom' => 'Ashburton', 'Previous_BT' => 'Ashburton'));
		Areacodes::create(array('area_code' => '01366', 'area_covered' => 'Downham Market', 'official_Ofcom' => 'Downham Market', 'Previous_BT' => 'Downham Market'));
		Areacodes::create(array('area_code' => '01367', 'area_covered' => 'Faringdon', 'official_Ofcom' => 'Faringdon', 'Previous_BT' => 'Faringdon'));
		Areacodes::create(array('area_code' => '01368', 'area_covered' => 'Dunbar', 'official_Ofcom' => 'Dunbar', 'Previous_BT' => 'Dunbar'));
		Areacodes::create(array('area_code' => '01369', 'area_covered' => 'Dunoon', 'official_Ofcom' => 'Dunoon', 'Previous_BT' => 'Dunoon'));
		Areacodes::create(array('area_code' => '01371', 'area_covered' => 'Great Dunmow', 'official_Ofcom' => 'Great Dunmow', 'Previous_BT' => 'Great Dunmow'));
		Areacodes::create(array('area_code' => '01372', 'area_covered' => 'Esher', 'official_Ofcom' => 'Esher', 'Previous_BT' => 'Esher (see also 01932)'));
		Areacodes::create(array('area_code' => '01373', 'area_covered' => 'Frome', 'official_Ofcom' => 'Frome', 'Previous_BT' => 'Frome'));
		Areacodes::create(array('area_code' => '01375', 'area_covered' => 'Grays Thurrock', 'official_Ofcom' => 'Grays Thurrock', 'Previous_BT' => 'Stanford-le-Hope (see also 01268)'));
		Areacodes::create(array('area_code' => '01376', 'area_covered' => 'Braintree', 'official_Ofcom' => 'Braintree', 'Previous_BT' => 'Braintree'));
		Areacodes::create(array('area_code' => '01377', 'area_covered' => 'Driffield', 'official_Ofcom' => 'Driffield', 'Previous_BT' => 'Driffield'));
		Areacodes::create(array('area_code' => '01379', 'area_covered' => 'Diss', 'official_Ofcom' => 'Diss', 'Previous_BT' => 'Diss'));
		Areacodes::create(array('area_code' => '01380', 'area_covered' => 'Devizes', 'official_Ofcom' => 'Devizes', 'Previous_BT' => 'Devizes'));
		Areacodes::create(array('area_code' => '01381', 'area_covered' => 'Fortrose', 'official_Ofcom' => 'Fortrose', 'Previous_BT' => 'Fortrose'));
		Areacodes::create(array('area_code' => '01382', 'area_covered' => 'Dundee', 'official_Ofcom' => 'Dundee', 'Previous_BT' => 'Dundee'));
		Areacodes::create(array('area_code' => '01383', 'area_covered' => 'Dunfermline', 'official_Ofcom' => 'Dunfermline', 'Previous_BT' => 'Dunfermline'));
		Areacodes::create(array('area_code' => '01384', 'area_covered' => 'Dudley', 'official_Ofcom' => 'Dudley', 'Previous_BT' => 'Stourbridge (see also 01562)'));
		Areacodes::create(array('area_code' => '01386', 'area_covered' => 'Evesham', 'official_Ofcom' => 'Evesham', 'Previous_BT' => 'Evesham'));
		Areacodes::create(array('area_code' => '01387', 'area_covered' => 'Dumfries', 'official_Ofcom' => 'Dumfries', 'Previous_BT' => 'Dumfries'));
		Areacodes::create(array('area_code' => '013873', 'area_covered' => 'Langholm', 'official_Ofcom' => 'Langholm', 'Previous_BT' => 'Langholm'));
		Areacodes::create(array('area_code' => '01388', 'area_covered' => 'Bishop Auckland / Stanhope', 'official_Ofcom' => 'Bishop Auckland / Stanhope', 'Previous_BT' => 'Bishop Auckland / Stanhope'));
		Areacodes::create(array('area_code' => '01389', 'area_covered' => 'Dumbarton', 'official_Ofcom' => 'Dumbarton', 'Previous_BT' => 'Dumbarton'));
		Areacodes::create(array('area_code' => '01392', 'area_covered' => 'Exeter', 'official_Ofcom' => 'Exeter', 'Previous_BT' => 'Exeter'));
		Areacodes::create(array('area_code' => '01394', 'area_covered' => 'Felixstowe', 'official_Ofcom' => 'Felixstowe', 'Previous_BT' => 'Shottisham'));
		Areacodes::create(array('area_code' => '01395', 'area_covered' => 'Budleigh Salterton', 'official_Ofcom' => 'Budleigh Salterton', 'Previous_BT' => 'Budleigh Salterton'));
		Areacodes::create(array('area_code' => '01397', 'area_covered' => 'Fort William', 'official_Ofcom' => 'Fort William', 'Previous_BT' => 'Fort William'));
		Areacodes::create(array('area_code' => '01398', 'area_covered' => 'Dulverton', 'official_Ofcom' => 'Dulverton', 'Previous_BT' => 'Dulverton'));
		Areacodes::create(array('area_code' => '01400', 'area_covered' => 'Honington', 'official_Ofcom' => 'Honington', 'Previous_BT' => 'Honington'));
		Areacodes::create(array('area_code' => '01403', 'area_covered' => 'Horsham', 'official_Ofcom' => 'Horsham', 'Previous_BT' => 'Horsham'));
		Areacodes::create(array('area_code' => '01404', 'area_covered' => 'Honiton', 'official_Ofcom' => 'Honiton', 'Previous_BT' => 'Honiton'));
		Areacodes::create(array('area_code' => '01405', 'area_covered' => 'Goole', 'official_Ofcom' => 'Goole', 'Previous_BT' => 'Goole'));
		Areacodes::create(array('area_code' => '01406', 'area_covered' => 'Holbeach', 'official_Ofcom' => 'Holbeach', 'Previous_BT' => 'Holbeach'));
		Areacodes::create(array('area_code' => '01407', 'area_covered' => 'Holyhead', 'official_Ofcom' => 'Holyhead', 'Previous_BT' => 'Holyhead'));
		Areacodes::create(array('area_code' => '01408', 'area_covered' => 'Golspie', 'official_Ofcom' => 'Golspie', 'Previous_BT' => 'Golspie'));
		Areacodes::create(array('area_code' => '01409', 'area_covered' => 'Holsworthy', 'official_Ofcom' => 'Holsworthy', 'Previous_BT' => 'Holsworthy'));
		Areacodes::create(array('area_code' => '0141', 'area_covered' => 'Glasgow', 'official_Ofcom' => 'Glasgow', 'Previous_BT' => 'Glasgow'));
		Areacodes::create(array('area_code' => '01420', 'area_covered' => 'Alton', 'official_Ofcom' => 'Alton', 'Previous_BT' => 'Alton'));
		Areacodes::create(array('area_code' => '01422', 'area_covered' => 'Halifax', 'official_Ofcom' => 'Halifax', 'Previous_BT' => 'Halifax'));
		Areacodes::create(array('area_code' => '01423', 'area_covered' => 'Boroughbridge / Harrogate', 'official_Ofcom' => 'Boroughbridge / Harrogate', 'Previous_BT' => 'Boroughbridge / Harrogate'));
		Areacodes::create(array('area_code' => '01424', 'area_covered' => 'Hastings', 'official_Ofcom' => 'Hastings', 'Previous_BT' => 'Hastings'));
		Areacodes::create(array('area_code' => '01425', 'area_covered' => 'Ringwood', 'official_Ofcom' => 'Ringwood', 'Previous_BT' => 'Burley'));
		Areacodes::create(array('area_code' => '01427', 'area_covered' => 'Gainsborough', 'official_Ofcom' => 'Gainsborough', 'Previous_BT' => 'Gainsborough'));
		Areacodes::create(array('area_code' => '01428', 'area_covered' => 'Haslemere', 'official_Ofcom' => 'Haslemere', 'Previous_BT' => 'Haslemere'));
		Areacodes::create(array('area_code' => '01429', 'area_covered' => 'Hartlepool', 'official_Ofcom' => 'Hartlepool', 'Previous_BT' => 'Hartlepool'));
		Areacodes::create(array('area_code' => '01430', 'area_covered' => 'Market Weighton / North Cave', 'official_Ofcom' => 'Market Weighton / North Cave', 'Previous_BT' => 'Market Weighton / North Cave'));
		Areacodes::create(array('area_code' => '01431', 'area_covered' => 'Helmsdale', 'official_Ofcom' => 'Helmsdale', 'Previous_BT' => 'Helmsdale'));
		Areacodes::create(array('area_code' => '01432', 'area_covered' => 'Hereford', 'official_Ofcom' => 'Hereford', 'Previous_BT' => 'Hereford'));
		Areacodes::create(array('area_code' => '01433', 'area_covered' => 'Hathersage', 'official_Ofcom' => 'Hathersage', 'Previous_BT' => 'Hathersage'));
		Areacodes::create(array('area_code' => '01434', 'area_covered' => 'Bellingham / Haltwhistle / Hexham', 'official_Ofcom' => 'Bellingham / Haltwhistle / Hexham', 'Previous_BT' => 'Bellingham / Haltwhistle / Hexham'));
		Areacodes::create(array('area_code' => '01435', 'area_covered' => 'Heathfield', 'official_Ofcom' => 'Heathfield', 'Previous_BT' => 'Heathfield'));
		Areacodes::create(array('area_code' => '01436', 'area_covered' => 'Helensburgh', 'official_Ofcom' => 'Helensburgh', 'Previous_BT' => 'Helensburgh'));
		Areacodes::create(array('area_code' => '01437', 'area_covered' => 'Clynderwen / Haverfordwest', 'official_Ofcom' => 'Clynderwen / Haverfordwest', 'Previous_BT' => 'Clynderwen / Haverfordwest'));
		Areacodes::create(array('area_code' => '01438', 'area_covered' => 'Stevenage', 'official_Ofcom' => 'Stevenage', 'Previous_BT' => 'Knebworth (see also 01920)'));
		Areacodes::create(array('area_code' => '01439', 'area_covered' => 'Helmsley', 'official_Ofcom' => 'Helmsley', 'Previous_BT' => 'Helmsley'));
		Areacodes::create(array('area_code' => '01440', 'area_covered' => 'Haverhill', 'official_Ofcom' => 'Haverhill', 'Previous_BT' => 'Haverhill'));
		Areacodes::create(array('area_code' => '01442', 'area_covered' => 'Hemel Hempstead', 'official_Ofcom' => 'Hemel Hempstead', 'Previous_BT' => 'Markyate (see also 01582)'));
		Areacodes::create(array('area_code' => '01443', 'area_covered' => 'Pontypridd', 'official_Ofcom' => 'Pontypridd', 'Previous_BT' => 'Pontypridd'));
		Areacodes::create(array('area_code' => '01444', 'area_covered' => 'Haywards Heath', 'official_Ofcom' => 'Haywards Heath', 'Previous_BT' => 'Haywards Heath'));
		Areacodes::create(array('area_code' => '01445', 'area_covered' => 'Gairloch', 'official_Ofcom' => 'Gairloch', 'Previous_BT' => 'Gairloch'));
		Areacodes::create(array('area_code' => '01446', 'area_covered' => 'Barry', 'official_Ofcom' => 'Barry', 'Previous_BT' => 'Barry'));
		Areacodes::create(array('area_code' => '01449', 'area_covered' => 'Stowmarket', 'official_Ofcom' => 'Stowmarket', 'Previous_BT' => 'Stowmarket'));
		Areacodes::create(array('area_code' => '01450', 'area_covered' => 'Hawick', 'official_Ofcom' => 'Hawick', 'Previous_BT' => 'Hawick'));
		Areacodes::create(array('area_code' => '01451', 'area_covered' => 'Stow-on-the-Wold', 'official_Ofcom' => 'Stow-on-the-Wold', 'Previous_BT' => 'Bourton-on-the-Water'));
		Areacodes::create(array('area_code' => '01452', 'area_covered' => 'Gloucester', 'official_Ofcom' => 'Gloucester', 'Previous_BT' => 'Gloucester'));
		Areacodes::create(array('area_code' => '01453', 'area_covered' => 'Dursley', 'official_Ofcom' => 'Dursley', 'Previous_BT' => 'Dursley'));
		Areacodes::create(array('area_code' => '01454', 'area_covered' => 'Chipping Sodbury', 'official_Ofcom' => 'Chipping Sodbury', 'Previous_BT' => 'Rangeworthy'));
		Areacodes::create(array('area_code' => '01455', 'area_covered' => 'Hinckley', 'official_Ofcom' => 'Hinckley', 'Previous_BT' => 'Hinckley'));
		Areacodes::create(array('area_code' => '01456', 'area_covered' => 'Glenurquhart', 'official_Ofcom' => 'Glenurquhart', 'Previous_BT' => 'Glenurquhart'));
		Areacodes::create(array('area_code' => '01457', 'area_covered' => 'Glossop', 'official_Ofcom' => 'Glossop', 'Previous_BT' => 'Glossop'));
		Areacodes::create(array('area_code' => '01458', 'area_covered' => 'Glastonbury', 'official_Ofcom' => 'Glastonbury', 'Previous_BT' => 'Glastonbury'));
		Areacodes::create(array('area_code' => '01460', 'area_covered' => 'Chard', 'official_Ofcom' => 'Chard', 'Previous_BT' => 'Chard'));
		Areacodes::create(array('area_code' => '01461', 'area_covered' => 'Gretna', 'official_Ofcom' => 'Gretna', 'Previous_BT' => 'Annan'));
		Areacodes::create(array('area_code' => '01462', 'area_covered' => 'Hitchin', 'official_Ofcom' => 'Hitchin', 'Previous_BT' => 'Hitchin'));
		Areacodes::create(array('area_code' => '01463', 'area_covered' => 'Inverness', 'official_Ofcom' => 'Inverness', 'Previous_BT' => 'Inverness'));
		Areacodes::create(array('area_code' => '01464', 'area_covered' => 'Insch', 'official_Ofcom' => 'Insch', 'Previous_BT' => 'Insch'));
		Areacodes::create(array('area_code' => '01465', 'area_covered' => 'Girvan', 'official_Ofcom' => 'Girvan', 'Previous_BT' => 'Girvan'));
		Areacodes::create(array('area_code' => '01466', 'area_covered' => 'Huntly', 'official_Ofcom' => 'Huntly', 'Previous_BT' => 'Huntly'));
		Areacodes::create(array('area_code' => '01467', 'area_covered' => 'Inverurie', 'official_Ofcom' => 'Inverurie', 'Previous_BT' => 'Inverurie'));
		Areacodes::create(array('area_code' => '01469', 'area_covered' => 'Killingholme', 'official_Ofcom' => 'Killingholme', 'Previous_BT' => 'Killingholme'));
		Areacodes::create(array('area_code' => '01470', 'area_covered' => 'Isle of Skye – Edinbane', 'official_Ofcom' => 'Isle of Skye – Edinbane', 'Previous_BT' => 'Isle of Skye – Edinbane'));
		Areacodes::create(array('area_code' => '01471', 'area_covered' => 'Isle of Skye – Broadford', 'official_Ofcom' => 'Isle of Skye – Broadford', 'Previous_BT' => 'Isle of Skye – Broadford'));
		Areacodes::create(array('area_code' => '01472', 'area_covered' => 'Grimsby', 'official_Ofcom' => 'Grimsby', 'Previous_BT' => 'Grimsby'));
		Areacodes::create(array('area_code' => '01473', 'area_covered' => 'Ipswich', 'official_Ofcom' => 'Ipswich', 'Previous_BT' => 'Ipswich'));
		Areacodes::create(array('area_code' => '01474', 'area_covered' => 'Gravesend', 'official_Ofcom' => 'Gravesend', 'Previous_BT' => 'Gravesend'));
		Areacodes::create(array('area_code' => '01475', 'area_covered' => 'Greenock', 'official_Ofcom' => 'Greenock', 'Previous_BT' => 'Greenock'));
		Areacodes::create(array('area_code' => '01476', 'area_covered' => 'Grantham', 'official_Ofcom' => 'Grantham', 'Previous_BT' => 'Grantham'));
		Areacodes::create(array('area_code' => '01477', 'area_covered' => 'Holmes Chapel', 'official_Ofcom' => 'Holmes Chapel', 'Previous_BT' => 'Congleton (see also 01260)'));
		Areacodes::create(array('area_code' => '01478', 'area_covered' => 'Isle of Skye – Portree', 'official_Ofcom' => 'Isle of Skye – Portree', 'Previous_BT' => 'Isle of Skye – Portree'));
		Areacodes::create(array('area_code' => '01479', 'area_covered' => 'Grantown-on-Spey', 'official_Ofcom' => 'Grantown-on-Spey', 'Previous_BT' => 'Grantown-on-Spey'));
		Areacodes::create(array('area_code' => '01480', 'area_covered' => 'Huntingdon', 'official_Ofcom' => 'Huntingdon', 'Previous_BT' => 'Huntingdon'));
		Areacodes::create(array('area_code' => '01481', 'area_covered' => 'Guernsey', 'official_Ofcom' => 'Guernsey', 'Previous_BT' => 'Guernsey'));
		Areacodes::create(array('area_code' => '01482', 'area_covered' => 'Hull', 'official_Ofcom' => 'Hull', 'Previous_BT' => 'Hull'));
		Areacodes::create(array('area_code' => '01483', 'area_covered' => 'Guildford', 'official_Ofcom' => 'Guildford', 'Previous_BT' => 'Guildford'));
		Areacodes::create(array('area_code' => '01484', 'area_covered' => 'Huddersfield', 'official_Ofcom' => 'Huddersfield', 'Previous_BT' => 'Huddersfield'));
		Areacodes::create(array('area_code' => '01485', 'area_covered' => 'Hunstanton', 'official_Ofcom' => 'Hunstanton', 'Previous_BT' => 'Docking'));
		Areacodes::create(array('area_code' => '01487', 'area_covered' => 'Warboys', 'official_Ofcom' => 'Warboys', 'Previous_BT' => 'Warboys'));
		Areacodes::create(array('area_code' => '01488', 'area_covered' => 'Hungerford', 'official_Ofcom' => 'Hungerford', 'Previous_BT' => 'Great Shefford'));
		Areacodes::create(array('area_code' => '01489', 'area_covered' => 'Bishops Waltham', 'official_Ofcom' => 'Bishops Waltham', 'Previous_BT' => 'Fareham (see also 01329)'));
		Areacodes::create(array('area_code' => '01490', 'area_covered' => 'Corwen', 'official_Ofcom' => 'Corwen', 'Previous_BT' => 'Corwen'));
		Areacodes::create(array('area_code' => '01491', 'area_covered' => 'Henley-on-Thames', 'official_Ofcom' => 'Henley-on-Thames', 'Previous_BT' => 'Nettlebed'));
		Areacodes::create(array('area_code' => '01492', 'area_covered' => 'Colwyn Bay', 'official_Ofcom' => 'Colwyn Bay', 'Previous_BT' => 'Colwyn Bay'));
		Areacodes::create(array('area_code' => '01493', 'area_covered' => 'Great Yarmouth', 'official_Ofcom' => 'Great Yarmouth', 'Previous_BT' => 'Great Yarmouth'));
		Areacodes::create(array('area_code' => '01494', 'area_covered' => 'High Wycombe', 'official_Ofcom' => 'High Wycombe', 'Previous_BT' => 'High Wycombe'));
		Areacodes::create(array('area_code' => '01495', 'area_covered' => 'Pontypool', 'official_Ofcom' => 'Pontypool', 'Previous_BT' => 'Pontypool'));
		Areacodes::create(array('area_code' => '01496', 'area_covered' => 'Port Ellen', 'official_Ofcom' => 'Port Ellen', 'Previous_BT' => 'Port Ellen'));
		Areacodes::create(array('area_code' => '01497', 'area_covered' => 'Hay-on-Wye', 'official_Ofcom' => 'Hay-on-Wye', 'Previous_BT' => 'Hay-on-Wye'));
		Areacodes::create(array('area_code' => '01499', 'area_covered' => 'Inveraray', 'official_Ofcom' => 'Inveraray', 'Previous_BT' => 'Inveraray'));
		Areacodes::create(array('area_code' => '01501', 'area_covered' => 'Harthill', 'official_Ofcom' => 'Harthill', 'Previous_BT' => 'Harthill'));
		Areacodes::create(array('area_code' => '01502', 'area_covered' => 'Lowestoft', 'official_Ofcom' => 'Lowestoft', 'Previous_BT' => 'Lowestoft'));
		Areacodes::create(array('area_code' => '01503', 'area_covered' => 'Looe', 'official_Ofcom' => 'Looe', 'Previous_BT' => 'Looe'));
		Areacodes::create(array('area_code' => '01505', 'area_covered' => 'Johnstone', 'official_Ofcom' => 'Johnstone', 'Previous_BT' => 'Johnstone'));
		Areacodes::create(array('area_code' => '01506', 'area_covered' => 'Bathgate', 'official_Ofcom' => 'Bathgate', 'Previous_BT' => 'Bathgate'));
		Areacodes::create(array('area_code' => '01507', 'area_covered' => 'Alford (Lincs) / Louth / Horncastle', 'official_Ofcom' => 'Alford (Lincs) / Louth / Spilsby', 'Previous_BT' => 'Alford (Lincs) / Louth / Spilsby (see also 01790)'));
		Areacodes::create(array('area_code' => '01508', 'area_covered' => 'Brooke', 'official_Ofcom' => 'Brooke', 'Previous_BT' => 'Brooke'));
		Areacodes::create(array('area_code' => '01509', 'area_covered' => 'Loughborough', 'official_Ofcom' => 'Loughborough', 'Previous_BT' => 'Loughborough'));
		Areacodes::create(array('area_code' => '0151', 'area_covered' => 'Liverpool', 'official_Ofcom' => 'Liverpool', 'Previous_BT' => 'Liverpool'));
		Areacodes::create(array('area_code' => '01520', 'area_covered' => 'Lochcarron', 'official_Ofcom' => 'Lochcarron', 'Previous_BT' => 'Lochcarron'));
		Areacodes::create(array('area_code' => '01522', 'area_covered' => 'Lincoln', 'official_Ofcom' => 'Lincoln', 'Previous_BT' => 'Lincoln'));
		Areacodes::create(array('area_code' => '01524', 'area_covered' => 'Lancaster', 'official_Ofcom' => 'Lancaster', 'Previous_BT' => 'Lancaster'));
		Areacodes::create(array('area_code' => '015242', 'area_covered' => 'Hornby', 'official_Ofcom' => 'Hornby', 'Previous_BT' => 'Hornby'));
		Areacodes::create(array('area_code' => '01525', 'area_covered' => 'Leighton Buzzard', 'official_Ofcom' => 'Leighton Buzzard', 'Previous_BT' => 'Leighton Buzzard'));
		Areacodes::create(array('area_code' => '01526', 'area_covered' => 'Martin', 'official_Ofcom' => 'Martin', 'Previous_BT' => 'Martin'));
		Areacodes::create(array('area_code' => '01527', 'area_covered' => 'Redditch', 'official_Ofcom' => 'Redditch', 'Previous_BT' => 'Redditch'));
		Areacodes::create(array('area_code' => '01528', 'area_covered' => 'Laggan', 'official_Ofcom' => 'Laggan', 'Previous_BT' => 'Laggan'));
		Areacodes::create(array('area_code' => '01529', 'area_covered' => 'Sleaford', 'official_Ofcom' => 'Sleaford', 'Previous_BT' => 'Sleaford'));
		Areacodes::create(array('area_code' => '01530', 'area_covered' => 'Coalville', 'official_Ofcom' => 'Coalville', 'Previous_BT' => 'Coalville'));
		Areacodes::create(array('area_code' => '01531', 'area_covered' => 'Ledbury', 'official_Ofcom' => 'Ledbury', 'Previous_BT' => 'Ledbury'));
		Areacodes::create(array('area_code' => '01534', 'area_covered' => 'Jersey', 'official_Ofcom' => 'Jersey', 'Previous_BT' => 'Jersey'));
		Areacodes::create(array('area_code' => '01535', 'area_covered' => 'Keighley', 'official_Ofcom' => 'Keighley', 'Previous_BT' => 'Keighley'));
		Areacodes::create(array('area_code' => '01536', 'area_covered' => 'Kettering', 'official_Ofcom' => 'Kettering', 'Previous_BT' => 'Kettering'));
		Areacodes::create(array('area_code' => '01538', 'area_covered' => 'Ipstones', 'official_Ofcom' => 'Ipstones', 'Previous_BT' => 'Ipstones'));
		Areacodes::create(array('area_code' => '01539', 'area_covered' => 'Kendal', 'official_Ofcom' => 'Kendal', 'Previous_BT' => 'Kendal'));
		Areacodes::create(array('area_code' => '015394', 'area_covered' => 'Hawkshead', 'official_Ofcom' => 'Hawkshead', 'Previous_BT' => 'Hawkshead'));
		Areacodes::create(array('area_code' => '015395', 'area_covered' => 'Grange-Over-Sands', 'official_Ofcom' => 'Grange-Over-Sands', 'Previous_BT' => 'Grange-Over-Sands'));
		Areacodes::create(array('area_code' => '015396', 'area_covered' => 'Sedbergh', 'official_Ofcom' => 'Sedbergh', 'Previous_BT' => 'Sedbergh'));
		Areacodes::create(array('area_code' => '01540', 'area_covered' => 'Kingussie', 'official_Ofcom' => 'Kingussie', 'Previous_BT' => 'Kingussie'));
		Areacodes::create(array('area_code' => '01542', 'area_covered' => 'Keith', 'official_Ofcom' => 'Keith', 'Previous_BT' => 'Keith'));
		Areacodes::create(array('area_code' => '01543', 'area_covered' => 'Cannock', 'official_Ofcom' => 'Cannock', 'Previous_BT' => 'Burntwood'));
		Areacodes::create(array('area_code' => '01544', 'area_covered' => 'Kington', 'official_Ofcom' => 'Kington', 'Previous_BT' => 'Kington'));
		Areacodes::create(array('area_code' => '01545', 'area_covered' => 'Llanarth', 'official_Ofcom' => 'Llanarth', 'Previous_BT' => 'Llanarth'));
		Areacodes::create(array('area_code' => '01546', 'area_covered' => 'Lochgilphead', 'official_Ofcom' => 'Lochgilphead', 'Previous_BT' => 'Lochgilphead'));
		Areacodes::create(array('area_code' => '01547', 'area_covered' => 'Knighton', 'official_Ofcom' => 'Knighton', 'Previous_BT' => 'Knighton'));
		Areacodes::create(array('area_code' => '01548', 'area_covered' => 'Kingsbridge', 'official_Ofcom' => 'Kingsbridge', 'Previous_BT' => 'Kingsbridge'));
		Areacodes::create(array('area_code' => '01549', 'area_covered' => 'Lairg', 'official_Ofcom' => 'Lairg', 'Previous_BT' => 'Lairg'));
		Areacodes::create(array('area_code' => '01550', 'area_covered' => 'Llandovery', 'official_Ofcom' => 'Llandovery', 'Previous_BT' => 'Llandovery'));
		Areacodes::create(array('area_code' => '01553', 'area_covered' => 'Kings Lynn', 'official_Ofcom' => 'Kings Lynn', 'Previous_BT' => 'Kings Lynn'));
		Areacodes::create(array('area_code' => '01554', 'area_covered' => 'Llanelli', 'official_Ofcom' => 'Llanelli', 'Previous_BT' => 'Llanelli'));
		Areacodes::create(array('area_code' => '01555', 'area_covered' => 'Lanark', 'official_Ofcom' => 'Lanark', 'Previous_BT' => 'Lanark'));
		Areacodes::create(array('area_code' => '01556', 'area_covered' => 'Castle Douglas', 'official_Ofcom' => 'Castle Douglas', 'Previous_BT' => 'Castle Douglas'));
		Areacodes::create(array('area_code' => '01557', 'area_covered' => 'Kirkcudbright', 'official_Ofcom' => 'Kirkcudbright', 'Previous_BT' => 'Kirkcudbright'));
		Areacodes::create(array('area_code' => '01558', 'area_covered' => 'Llandeilo', 'official_Ofcom' => 'Llandeilo', 'Previous_BT' => 'Llandeilo'));
		Areacodes::create(array('area_code' => '01559', 'area_covered' => 'Llandysul', 'official_Ofcom' => 'Llandysul', 'Previous_BT' => 'Llandysul'));
		Areacodes::create(array('area_code' => '01560', 'area_covered' => 'Moscow', 'official_Ofcom' => 'Moscow', 'Previous_BT' => 'Moscow'));
		Areacodes::create(array('area_code' => '01561', 'area_covered' => 'Laurencekirk', 'official_Ofcom' => 'Laurencekirk', 'Previous_BT' => 'Fordoun'));
		Areacodes::create(array('area_code' => '01562', 'area_covered' => 'Kidderminster', 'official_Ofcom' => 'Kidderminster', 'Previous_BT' => 'Stourbridge (see also 01384)'));
		Areacodes::create(array('area_code' => '01563', 'area_covered' => 'Kilmarnock', 'official_Ofcom' => 'Kilmarnock', 'Previous_BT' => 'Kilmarnock'));
		Areacodes::create(array('area_code' => '01564', 'area_covered' => 'Lapworth', 'official_Ofcom' => 'Lapworth', 'Previous_BT' => 'Lapworth'));
		Areacodes::create(array('area_code' => '01565', 'area_covered' => 'Knutsford', 'official_Ofcom' => 'Knutsford', 'Previous_BT' => 'Knutsford'));
		Areacodes::create(array('area_code' => '01566', 'area_covered' => 'Launceston', 'official_Ofcom' => 'Launceston', 'Previous_BT' => 'Launceston'));
		Areacodes::create(array('area_code' => '01567', 'area_covered' => 'Killin', 'official_Ofcom' => 'Killin', 'Previous_BT' => 'Killin'));
		Areacodes::create(array('area_code' => '01568', 'area_covered' => 'Leominster', 'official_Ofcom' => 'Leominster', 'Previous_BT' => 'Leominster'));
		Areacodes::create(array('area_code' => '01569', 'area_covered' => 'Stonehaven', 'official_Ofcom' => 'Stonehaven', 'Previous_BT' => 'Stonehaven'));
		Areacodes::create(array('area_code' => '01570', 'area_covered' => 'Lampeter', 'official_Ofcom' => 'Lampeter', 'Previous_BT' => 'Lampeter'));
		Areacodes::create(array('area_code' => '01571', 'area_covered' => 'Lochinver', 'official_Ofcom' => 'Lochinver', 'Previous_BT' => 'Lochinver'));
		Areacodes::create(array('area_code' => '01572', 'area_covered' => 'Oakham', 'official_Ofcom' => 'Oakham', 'Previous_BT' => 'Oakham'));
		Areacodes::create(array('area_code' => '01573', 'area_covered' => 'Kelso', 'official_Ofcom' => 'Kelso', 'Previous_BT' => 'Kelso'));
		Areacodes::create(array('area_code' => '01575', 'area_covered' => 'Kirriemuir', 'official_Ofcom' => 'Kirriemuir', 'Previous_BT' => 'Kirriemuir'));
		Areacodes::create(array('area_code' => '01576', 'area_covered' => 'Lockerbie', 'official_Ofcom' => 'Lockerbie', 'Previous_BT' => 'Lockerbie'));
		Areacodes::create(array('area_code' => '01577', 'area_covered' => 'Kinross', 'official_Ofcom' => 'Kinross', 'Previous_BT' => 'Kinross'));
		Areacodes::create(array('area_code' => '01578', 'area_covered' => 'Lauder', 'official_Ofcom' => 'Lauder', 'Previous_BT' => 'Lauder'));
		Areacodes::create(array('area_code' => '01579', 'area_covered' => 'Liskeard', 'official_Ofcom' => 'Liskeard', 'Previous_BT' => 'Liskeard'));
		Areacodes::create(array('area_code' => '01580', 'area_covered' => 'Cranbrook', 'official_Ofcom' => 'Cranbrook', 'Previous_BT' => 'Cranbrook'));
		Areacodes::create(array('area_code' => '01581', 'area_covered' => 'New Luce', 'official_Ofcom' => 'New Luce', 'Previous_BT' => 'New Luce'));
		Areacodes::create(array('area_code' => '01582', 'area_covered' => 'Luton', 'official_Ofcom' => 'Luton', 'Previous_BT' => 'Markyate (see also 01442)'));
		Areacodes::create(array('area_code' => '01583', 'area_covered' => 'Carradale', 'official_Ofcom' => 'Carradale', 'Previous_BT' => 'Carradale'));
		Areacodes::create(array('area_code' => '01584', 'area_covered' => 'Ludlow', 'official_Ofcom' => 'Ludlow', 'Previous_BT' => 'Ludlow'));
		Areacodes::create(array('area_code' => '01586', 'area_covered' => 'Campbeltown', 'official_Ofcom' => 'Campbeltown', 'Previous_BT' => 'Campbeltown'));
		Areacodes::create(array('area_code' => '01588', 'area_covered' => 'Bishops Castle', 'official_Ofcom' => 'Bishops Castle', 'Previous_BT' => 'Craven Arms'));
		Areacodes::create(array('area_code' => '01590', 'area_covered' => 'Lymington', 'official_Ofcom' => 'Lymington', 'Previous_BT' => 'Lymington'));
		Areacodes::create(array('area_code' => '01591', 'area_covered' => 'Llanwrtyd Wells', 'official_Ofcom' => 'Llanwrtyd Wells', 'Previous_BT' => 'Llanwrtyd Wells'));
		Areacodes::create(array('area_code' => '01592', 'area_covered' => 'Kirkcaldy', 'official_Ofcom' => 'Kirkcaldy', 'Previous_BT' => 'Kirkcaldy'));
		Areacodes::create(array('area_code' => '01593', 'area_covered' => 'Lybster', 'official_Ofcom' => 'Lybster', 'Previous_BT' => 'Lybster'));
		Areacodes::create(array('area_code' => '01594', 'area_covered' => 'Lydney', 'official_Ofcom' => 'Lydney', 'Previous_BT' => 'Lydney'));
		Areacodes::create(array('area_code' => '01595', 'area_covered' => 'Lerwick, Shetland Islands', 'official_Ofcom' => 'Lerwick / Foula / Fair Isle', 'Previous_BT' => 'Lerwick / Foula / Fair Isle'));
		Areacodes::create(array('area_code' => '01597', 'area_covered' => 'Llandrindod Wells', 'official_Ofcom' => 'Llandrindod Wells', 'Previous_BT' => 'Llandrindod Wells'));
		Areacodes::create(array('area_code' => '01598', 'area_covered' => 'Lynton', 'official_Ofcom' => 'Lynton', 'Previous_BT' => 'Brayford'));
		Areacodes::create(array('area_code' => '01599', 'area_covered' => 'Kyle', 'official_Ofcom' => 'Kyle', 'Previous_BT' => 'Kyle'));
		Areacodes::create(array('area_code' => '01600', 'area_covered' => 'Monmouth', 'official_Ofcom' => 'Monmouth', 'Previous_BT' => 'Monmouth'));
		Areacodes::create(array('area_code' => '01603', 'area_covered' => 'Norwich', 'official_Ofcom' => 'Norwich', 'Previous_BT' => 'Norwich'));
		Areacodes::create(array('area_code' => '01604', 'area_covered' => 'Northampton', 'official_Ofcom' => 'Northampton', 'Previous_BT' => 'Northampton'));
		Areacodes::create(array('area_code' => '01606', 'area_covered' => 'Northwich', 'official_Ofcom' => 'Northwich', 'Previous_BT' => 'Northwich'));
		Areacodes::create(array('area_code' => '01608', 'area_covered' => 'Chipping Norton', 'official_Ofcom' => 'Chipping Norton', 'Previous_BT' => 'Chipping Norton'));
		Areacodes::create(array('area_code' => '01609', 'area_covered' => 'Northallerton', 'official_Ofcom' => 'Northallerton', 'Previous_BT' => 'Northallerton'));
		Areacodes::create(array('area_code' => '0161', 'area_covered' => 'Manchester', 'official_Ofcom' => 'Manchester', 'Previous_BT' => 'Manchester'));
		Areacodes::create(array('area_code' => '01620', 'area_covered' => 'North Berwick', 'official_Ofcom' => 'North Berwick', 'Previous_BT' => 'North Berwick'));
		Areacodes::create(array('area_code' => '01621', 'area_covered' => 'Maldon', 'official_Ofcom' => 'Maldon', 'Previous_BT' => 'Maldon'));
		Areacodes::create(array('area_code' => '01622', 'area_covered' => 'Maidstone', 'official_Ofcom' => 'Maidstone', 'Previous_BT' => 'Maidstone'));
		Areacodes::create(array('area_code' => '01623', 'area_covered' => 'Mansfield', 'official_Ofcom' => 'Mansfield', 'Previous_BT' => 'Mansfield'));
		Areacodes::create(array('area_code' => '01624', 'area_covered' => 'Isle of Man', 'official_Ofcom' => 'Isle of Man', 'Previous_BT' => 'Isle of Man'));
		Areacodes::create(array('area_code' => '01625', 'area_covered' => 'Macclesfield', 'official_Ofcom' => 'Macclesfield', 'Previous_BT' => 'Macclesfield'));
		Areacodes::create(array('area_code' => '01626', 'area_covered' => 'Newton Abbot', 'official_Ofcom' => 'Newton Abbot', 'Previous_BT' => 'Newton Abbot'));
		Areacodes::create(array('area_code' => '01628', 'area_covered' => 'Maidenhead', 'official_Ofcom' => 'Maidenhead', 'Previous_BT' => 'Maidenhead'));
		Areacodes::create(array('area_code' => '01629', 'area_covered' => 'Matlock', 'official_Ofcom' => 'Matlock', 'Previous_BT' => 'Matlock'));
		Areacodes::create(array('area_code' => '01630', 'area_covered' => 'Market Drayton', 'official_Ofcom' => 'Market Drayton', 'Previous_BT' => 'Market Drayton'));
		Areacodes::create(array('area_code' => '01631', 'area_covered' => 'Oban', 'official_Ofcom' => 'Oban', 'Previous_BT' => 'Oban'));
		Areacodes::create(array('area_code' => '01633', 'area_covered' => 'Newport', 'official_Ofcom' => 'Newport', 'Previous_BT' => 'Newport'));
		Areacodes::create(array('area_code' => '01634', 'area_covered' => 'Medway', 'official_Ofcom' => 'Medway', 'Previous_BT' => 'Medway'));
		Areacodes::create(array('area_code' => '01635', 'area_covered' => 'Newbury', 'official_Ofcom' => 'Newbury', 'Previous_BT' => 'Newbury'));
		Areacodes::create(array('area_code' => '01636', 'area_covered' => 'Newark', 'official_Ofcom' => 'Newark', 'Previous_BT' => 'Newark'));
		Areacodes::create(array('area_code' => '01637', 'area_covered' => 'Newquay', 'official_Ofcom' => 'Newquay', 'Previous_BT' => 'Newquay (see also 01841)'));
		Areacodes::create(array('area_code' => '01638', 'area_covered' => 'Newmarket', 'official_Ofcom' => 'Newmarket', 'Previous_BT' => 'Newmarket'));
		Areacodes::create(array('area_code' => '01639', 'area_covered' => 'Neath', 'official_Ofcom' => 'Neath', 'Previous_BT' => 'Neath'));
		Areacodes::create(array('area_code' => '01641', 'area_covered' => 'Strathy', 'official_Ofcom' => 'Strathy', 'Previous_BT' => 'Strathy'));
		Areacodes::create(array('area_code' => '01642', 'area_covered' => 'Middlesbrough', 'official_Ofcom' => 'Middlesbrough', 'Previous_BT' => 'Middlesbrough'));
		Areacodes::create(array('area_code' => '01643', 'area_covered' => 'Minehead', 'official_Ofcom' => 'Minehead', 'Previous_BT' => 'Minehead'));
		Areacodes::create(array('area_code' => '01644', 'area_covered' => 'New Galloway', 'official_Ofcom' => 'New Galloway', 'Previous_BT' => 'New Galloway'));
		Areacodes::create(array('area_code' => '01646', 'area_covered' => 'Milford Haven', 'official_Ofcom' => 'Milford Haven', 'Previous_BT' => 'Milford Haven'));
		Areacodes::create(array('area_code' => '01647', 'area_covered' => 'Moretonhampstead', 'official_Ofcom' => 'Moretonhampstead', 'Previous_BT' => 'Moretonhampstead'));
		Areacodes::create(array('area_code' => '01650', 'area_covered' => 'Cemmaes Road', 'official_Ofcom' => 'Cemmaes Road', 'Previous_BT' => 'Cemmaes Road'));
		Areacodes::create(array('area_code' => '01651', 'area_covered' => 'Oldmeldrum', 'official_Ofcom' => 'Oldmeldrum', 'Previous_BT' => 'Oldmeldrum'));
		Areacodes::create(array('area_code' => '01652', 'area_covered' => 'Brigg', 'official_Ofcom' => 'Brigg', 'Previous_BT' => 'Brigg'));
		Areacodes::create(array('area_code' => '01653', 'area_covered' => 'Malton', 'official_Ofcom' => 'Malton', 'Previous_BT' => 'Malton'));
		Areacodes::create(array('area_code' => '01654', 'area_covered' => 'Machynlleth', 'official_Ofcom' => 'Machynlleth', 'Previous_BT' => 'Machynlleth'));
		Areacodes::create(array('area_code' => '01655', 'area_covered' => 'Maybole', 'official_Ofcom' => 'Maybole', 'Previous_BT' => 'Maybole'));
		Areacodes::create(array('area_code' => '01656', 'area_covered' => 'Bridgend', 'official_Ofcom' => 'Bridgend', 'Previous_BT' => 'Bridgend'));
		Areacodes::create(array('area_code' => '01659', 'area_covered' => 'Sanquhar', 'official_Ofcom' => 'Sanquhar', 'Previous_BT' => 'Sanquhar'));
		Areacodes::create(array('area_code' => '01661', 'area_covered' => 'Prudhoe', 'official_Ofcom' => 'Prudhoe', 'Previous_BT' => 'Wylam'));
		Areacodes::create(array('area_code' => '01663', 'area_covered' => 'New Mills', 'official_Ofcom' => 'New Mills', 'Previous_BT' => 'New Mills'));
		Areacodes::create(array('area_code' => '01664', 'area_covered' => 'Melton Mowbray', 'official_Ofcom' => 'Melton Mowbray', 'Previous_BT' => 'Melton Mowbray'));
		Areacodes::create(array('area_code' => '01665', 'area_covered' => 'Alnwick', 'official_Ofcom' => 'Alnwick', 'Previous_BT' => 'Alnwick'));
		Areacodes::create(array('area_code' => '01666', 'area_covered' => 'Malmesbury', 'official_Ofcom' => 'Malmesbury', 'Previous_BT' => 'Malmesbury'));
		Areacodes::create(array('area_code' => '01667', 'area_covered' => 'Nairn', 'official_Ofcom' => 'Nairn', 'Previous_BT' => 'Nairn'));
		Areacodes::create(array('area_code' => '01668', 'area_covered' => 'Bamburgh', 'official_Ofcom' => 'Bamburgh', 'Previous_BT' => 'Belford'));
		Areacodes::create(array('area_code' => '01669', 'area_covered' => 'Rothbury', 'official_Ofcom' => 'Rothbury', 'Previous_BT' => 'Rothbury'));
		Areacodes::create(array('area_code' => '01670', 'area_covered' => 'Morpeth', 'official_Ofcom' => 'Morpeth', 'Previous_BT' => 'Morpeth'));
		Areacodes::create(array('area_code' => '01671', 'area_covered' => 'Newton Stewart', 'official_Ofcom' => 'Newton Stewart', 'Previous_BT' => 'Newton Stewart'));
		Areacodes::create(array('area_code' => '01672', 'area_covered' => 'Marlborough', 'official_Ofcom' => 'Marlborough', 'Previous_BT' => 'Marlborough'));
		Areacodes::create(array('area_code' => '01673', 'area_covered' => 'Market Rasen', 'official_Ofcom' => 'Market Rasen', 'Previous_BT' => 'Market Rasen'));
		Areacodes::create(array('area_code' => '01674', 'area_covered' => 'Montrose', 'official_Ofcom' => 'Montrose', 'Previous_BT' => 'Montrose'));
		Areacodes::create(array('area_code' => '01675', 'area_covered' => 'Coleshill', 'official_Ofcom' => 'Coleshill', 'Previous_BT' => 'Meriden (see also 01676)'));
		Areacodes::create(array('area_code' => '01676', 'area_covered' => 'Meriden', 'official_Ofcom' => 'Meriden', 'Previous_BT' => 'Meriden (see also 01675)'));
		Areacodes::create(array('area_code' => '01677', 'area_covered' => 'Bedale', 'official_Ofcom' => 'Bedale', 'Previous_BT' => 'Bedale'));
		Areacodes::create(array('area_code' => '01678', 'area_covered' => 'Bala', 'official_Ofcom' => 'Bala', 'Previous_BT' => 'Bala'));
		Areacodes::create(array('area_code' => '01680', 'area_covered' => 'Isle of Mull – Craignure', 'official_Ofcom' => 'Isle of Mull – Craignure', 'Previous_BT' => 'Isle of Mull – Craignure'));
		Areacodes::create(array('area_code' => '01681', 'area_covered' => 'Isle of Mull – Fionnphort', 'official_Ofcom' => 'Isle of Mull – Fionnphort', 'Previous_BT' => 'Isle of Mull – Fionnphort'));
		Areacodes::create(array('area_code' => '01683', 'area_covered' => 'Moffat', 'official_Ofcom' => 'Moffat', 'Previous_BT' => 'Moffat'));
		Areacodes::create(array('area_code' => '01684', 'area_covered' => 'Malvern', 'official_Ofcom' => 'Malvern', 'Previous_BT' => 'Hanley Swan'));
		Areacodes::create(array('area_code' => '01685', 'area_covered' => 'Merthyr Tydfil', 'official_Ofcom' => 'Merthyr Tydfil', 'Previous_BT' => 'Merthyr Tydfil'));
		Areacodes::create(array('area_code' => '01686', 'area_covered' => 'Llanidloes / Newtown', 'official_Ofcom' => 'Llanidloes / Newtown', 'Previous_BT' => 'Llanidloes / Newtown'));
		Areacodes::create(array('area_code' => '01687', 'area_covered' => 'Mallaig', 'official_Ofcom' => 'Mallaig', 'Previous_BT' => 'Mallaig'));
		Areacodes::create(array('area_code' => '01688', 'area_covered' => 'Isle of Mull – Tobermory', 'official_Ofcom' => 'Isle of Mull – Tobermory', 'Previous_BT' => 'Isle of Mull – Tobermory'));
		Areacodes::create(array('area_code' => '01689', 'area_covered' => 'Orpington', 'official_Ofcom' => 'Orpington', 'Previous_BT' => 'Swanley (see also 01322 and 01959)'));
		Areacodes::create(array('area_code' => '01690', 'area_covered' => 'Betws-y-Coed', 'official_Ofcom' => 'Betws-y-Coed', 'Previous_BT' => 'Betws-y-Coed'));
		Areacodes::create(array('area_code' => '01691', 'area_covered' => 'Oswestry', 'official_Ofcom' => 'Oswestry', 'Previous_BT' => 'Oswestry'));
		Areacodes::create(array('area_code' => '01692', 'area_covered' => 'North Walsham', 'official_Ofcom' => 'North Walsham', 'Previous_BT' => 'North Walsham'));
		Areacodes::create(array('area_code' => '01694', 'area_covered' => 'Church Stretton', 'official_Ofcom' => 'Church Stretton', 'Previous_BT' => 'Church Stretton'));
		Areacodes::create(array('area_code' => '01695', 'area_covered' => 'Skelmersdale', 'official_Ofcom' => 'Skelmersdale', 'Previous_BT' => 'Rainford (see also 01744)'));
		Areacodes::create(array('area_code' => '01697', 'area_covered' => 'Brampton (6 figure numbers)', 'official_Ofcom' => 'Brampton', 'Previous_BT' => 'Not listed'));
		Areacodes::create(array('area_code' => '016973', 'area_covered' => 'Wigton', 'official_Ofcom' => 'Wigton', 'Previous_BT' => 'Wigton'));
		Areacodes::create(array('area_code' => '016974', 'area_covered' => 'Raughton Head', 'official_Ofcom' => 'Raughton Head', 'Previous_BT' => 'Raughton Head'));
		Areacodes::create(array('area_code' => '016977', 'area_covered' => 'Brampton (4 and 5 figure numbers)', 'official_Ofcom' => 'Not listed', 'Previous_BT' => 'Brampton'));
		Areacodes::create(array('area_code' => '01698', 'area_covered' => 'Motherwell', 'official_Ofcom' => 'Motherwell', 'Previous_BT' => 'Motherwell'));
		Areacodes::create(array('area_code' => '01700', 'area_covered' => 'Rothesay', 'official_Ofcom' => 'Rothesay', 'Previous_BT' => 'Rothesay'));
		Areacodes::create(array('area_code' => '01702', 'area_covered' => 'Southend-on-Sea', 'official_Ofcom' => 'Southend-on-Sea', 'Previous_BT' => 'Southend-on-Sea'));
		Areacodes::create(array('area_code' => '01704', 'area_covered' => 'Southport', 'official_Ofcom' => 'Southport', 'Previous_BT' => 'Southport'));
		Areacodes::create(array('area_code' => '01706', 'area_covered' => 'Rochdale', 'official_Ofcom' => 'Rochdale', 'Previous_BT' => 'Rochdale'));
		Areacodes::create(array('area_code' => '01707', 'area_covered' => 'Welwyn Garden City', 'official_Ofcom' => 'Welwyn Garden City', 'Previous_BT' => 'Colney Heath (see also 01727)'));
		Areacodes::create(array('area_code' => '01708', 'area_covered' => 'Romford', 'official_Ofcom' => 'Romford', 'Previous_BT' => 'Romford'));
		Areacodes::create(array('area_code' => '01709', 'area_covered' => 'Rotherham', 'official_Ofcom' => 'Rotherham', 'Previous_BT' => 'Rotherham'));
		Areacodes::create(array('area_code' => '01720', 'area_covered' => 'Isles of Scilly', 'official_Ofcom' => 'Isles of Scilly', 'Previous_BT' => 'Scillonia'));
		Areacodes::create(array('area_code' => '01721', 'area_covered' => 'Peebles', 'official_Ofcom' => 'Peebles', 'Previous_BT' => 'Peebles'));
		Areacodes::create(array('area_code' => '01722', 'area_covered' => 'Salisbury', 'official_Ofcom' => 'Salisbury', 'Previous_BT' => 'Salisbury'));
		Areacodes::create(array('area_code' => '01723', 'area_covered' => 'Scarborough', 'official_Ofcom' => 'Scarborough', 'Previous_BT' => 'Scarborough'));
		Areacodes::create(array('area_code' => '01724', 'area_covered' => 'Scunthorpe', 'official_Ofcom' => 'Scunthorpe', 'Previous_BT' => 'Scunthorpe'));
		Areacodes::create(array('area_code' => '01725', 'area_covered' => 'Rockbourne', 'official_Ofcom' => 'Rockbourne', 'Previous_BT' => 'Rockbourne'));
		Areacodes::create(array('area_code' => '01726', 'area_covered' => 'St Austell', 'official_Ofcom' => 'St Austell', 'Previous_BT' => 'St Austell'));
		Areacodes::create(array('area_code' => '01727', 'area_covered' => 'St Albans', 'official_Ofcom' => 'St Albans', 'Previous_BT' => 'Colney Heath (see also 01707)'));
		Areacodes::create(array('area_code' => '01728', 'area_covered' => 'Saxmundham', 'official_Ofcom' => 'Saxmundham', 'Previous_BT' => 'Saxmundham'));
		Areacodes::create(array('area_code' => '01729', 'area_covered' => 'Settle', 'official_Ofcom' => 'Settle', 'Previous_BT' => 'Settle'));
		Areacodes::create(array('area_code' => '01730', 'area_covered' => 'Petersfield', 'official_Ofcom' => 'Petersfield', 'Previous_BT' => 'Petersfield'));
		Areacodes::create(array('area_code' => '01732', 'area_covered' => 'Sevenoaks', 'official_Ofcom' => 'Sevenoaks', 'Previous_BT' => 'Sevenoaks'));
		Areacodes::create(array('area_code' => '01733', 'area_covered' => 'Peterborough', 'official_Ofcom' => 'Peterborough', 'Previous_BT' => 'Peterborough'));
		Areacodes::create(array('area_code' => '01736', 'area_covered' => 'Penzance', 'official_Ofcom' => 'Penzance', 'Previous_BT' => 'Penzance'));
		Areacodes::create(array('area_code' => '01737', 'area_covered' => 'Redhill', 'official_Ofcom' => 'Redhill', 'Previous_BT' => 'Merstham (see also 01883)'));
		Areacodes::create(array('area_code' => '01738', 'area_covered' => 'Perth', 'official_Ofcom' => 'Perth', 'Previous_BT' => 'Perth'));
		Areacodes::create(array('area_code' => '01740', 'area_covered' => 'Sedgefield', 'official_Ofcom' => 'Sedgefield', 'Previous_BT' => 'Sedgefield'));
		Areacodes::create(array('area_code' => '01743', 'area_covered' => 'Shrewsbury', 'official_Ofcom' => 'Shrewsbury', 'Previous_BT' => 'Shrewsbury'));
		Areacodes::create(array('area_code' => '01744', 'area_covered' => 'St Helens', 'official_Ofcom' => 'St Helens', 'Previous_BT' => 'Rainford (see also 01695)'));
		Areacodes::create(array('area_code' => '01745', 'area_covered' => 'Rhyl', 'official_Ofcom' => 'Rhyl', 'Previous_BT' => 'Rhyl'));
		Areacodes::create(array('area_code' => '01746', 'area_covered' => 'Bridgnorth', 'official_Ofcom' => 'Bridgnorth', 'Previous_BT' => 'Bridgnorth'));
		Areacodes::create(array('area_code' => '01747', 'area_covered' => 'Shaftesbury', 'official_Ofcom' => 'Shaftesbury', 'Previous_BT' => 'Shaftesbury'));
		Areacodes::create(array('area_code' => '01748', 'area_covered' => 'Richmond', 'official_Ofcom' => 'Richmond', 'Previous_BT' => 'Richmond'));
		Areacodes::create(array('area_code' => '01749', 'area_covered' => 'Shepton Mallet', 'official_Ofcom' => 'Shepton Mallet', 'Previous_BT' => 'Shepton Mallet'));
		Areacodes::create(array('area_code' => '01750', 'area_covered' => 'Selkirk', 'official_Ofcom' => 'Selkirk', 'Previous_BT' => 'Selkirk'));
		Areacodes::create(array('area_code' => '01751', 'area_covered' => 'Pickering', 'official_Ofcom' => 'Pickering', 'Previous_BT' => 'Pickering'));
		Areacodes::create(array('area_code' => '01752', 'area_covered' => 'Plymouth', 'official_Ofcom' => 'Plymouth', 'Previous_BT' => 'Plymouth'));
		Areacodes::create(array('area_code' => '01753', 'area_covered' => 'Slough', 'official_Ofcom' => 'Slough', 'Previous_BT' => 'Iver (see also 01784 and 01895)'));
		Areacodes::create(array('area_code' => '01754', 'area_covered' => 'Skegness', 'official_Ofcom' => 'Skegness', 'Previous_BT' => 'Skegness'));
		Areacodes::create(array('area_code' => '01756', 'area_covered' => 'Skipton', 'official_Ofcom' => 'Skipton', 'Previous_BT' => 'Skipton'));
		Areacodes::create(array('area_code' => '01757', 'area_covered' => 'Selby', 'official_Ofcom' => 'Selby', 'Previous_BT' => 'Selby'));
		Areacodes::create(array('area_code' => '01758', 'area_covered' => 'Pwllheli', 'official_Ofcom' => 'Pwllheli', 'Previous_BT' => 'Pwllheli'));
		Areacodes::create(array('area_code' => '01759', 'area_covered' => 'Pocklington', 'official_Ofcom' => 'Pocklington', 'Previous_BT' => 'Pocklington'));
		Areacodes::create(array('area_code' => '01760', 'area_covered' => 'Swaffham', 'official_Ofcom' => 'Swaffham', 'Previous_BT' => 'Swaffham'));
		Areacodes::create(array('area_code' => '01761', 'area_covered' => 'Temple Cloud', 'official_Ofcom' => 'Temple Cloud', 'Previous_BT' => 'Temple Cloud'));
		Areacodes::create(array('area_code' => '01763', 'area_covered' => 'Royston', 'official_Ofcom' => 'Royston', 'Previous_BT' => 'Royston'));
		Areacodes::create(array('area_code' => '01764', 'area_covered' => 'Crieff', 'official_Ofcom' => 'Crieff', 'Previous_BT' => 'Crieff'));
		Areacodes::create(array('area_code' => '01765', 'area_covered' => 'Ripon', 'official_Ofcom' => 'Ripon', 'Previous_BT' => 'Ripon'));
		Areacodes::create(array('area_code' => '01766', 'area_covered' => 'Porthmadog', 'official_Ofcom' => 'Porthmadog', 'Previous_BT' => 'Porthmadog'));
		Areacodes::create(array('area_code' => '01767', 'area_covered' => 'Sandy', 'official_Ofcom' => 'Sandy', 'Previous_BT' => 'Sandy'));
		Areacodes::create(array('area_code' => '01768', 'area_covered' => 'Penrith', 'official_Ofcom' => 'Penrith', 'Previous_BT' => 'Penrith'));
		Areacodes::create(array('area_code' => '017683', 'area_covered' => 'Appleby', 'official_Ofcom' => 'Appleby', 'Previous_BT' => 'Appleby'));
		Areacodes::create(array('area_code' => '017684', 'area_covered' => 'Pooley Bridge', 'official_Ofcom' => 'Pooley Bridge', 'Previous_BT' => 'Pooley Bridge'));
		Areacodes::create(array('area_code' => '017687', 'area_covered' => 'Keswick', 'official_Ofcom' => 'Keswick', 'Previous_BT' => 'Keswick'));
		Areacodes::create(array('area_code' => '01769', 'area_covered' => 'South Molton', 'official_Ofcom' => 'South Molton', 'Previous_BT' => 'South Molton'));
		Areacodes::create(array('area_code' => '01770', 'area_covered' => 'Isle of Arran', 'official_Ofcom' => 'Isle of Arran', 'Previous_BT' => 'Brodick'));
		Areacodes::create(array('area_code' => '01771', 'area_covered' => 'Maud', 'official_Ofcom' => 'Maud', 'Previous_BT' => 'Maud'));
		Areacodes::create(array('area_code' => '01772', 'area_covered' => 'Preston', 'official_Ofcom' => 'Preston', 'Previous_BT' => 'Preston'));
		Areacodes::create(array('area_code' => '01773', 'area_covered' => 'Ripley', 'official_Ofcom' => 'Ripley', 'Previous_BT' => 'Ripley'));
		Areacodes::create(array('area_code' => '01775', 'area_covered' => 'Spalding', 'official_Ofcom' => 'Spalding', 'Previous_BT' => 'Spalding'));
		Areacodes::create(array('area_code' => '01776', 'area_covered' => 'Stranraer', 'official_Ofcom' => 'Stranraer', 'Previous_BT' => 'Stranraer'));
		Areacodes::create(array('area_code' => '01777', 'area_covered' => 'Retford', 'official_Ofcom' => 'Retford', 'Previous_BT' => 'Retford'));
		Areacodes::create(array('area_code' => '01778', 'area_covered' => 'Bourne', 'official_Ofcom' => 'Bourne', 'Previous_BT' => 'Bourne'));
		Areacodes::create(array('area_code' => '01779', 'area_covered' => 'Peterhead', 'official_Ofcom' => 'Peterhead', 'Previous_BT' => 'Peterhead'));
		Areacodes::create(array('area_code' => '01780', 'area_covered' => 'Stamford', 'official_Ofcom' => 'Stamford', 'Previous_BT' => 'Stamford'));
		Areacodes::create(array('area_code' => '01782', 'area_covered' => 'Stoke-on-Trent', 'official_Ofcom' => 'Stoke-on-Trent', 'Previous_BT' => 'Stoke-on-Trent'));
		Areacodes::create(array('area_code' => '01784', 'area_covered' => 'Staines', 'official_Ofcom' => 'Staines', 'Previous_BT' => 'Iver (see also 01753 and 01895)'));
		Areacodes::create(array('area_code' => '01785', 'area_covered' => 'Stafford', 'official_Ofcom' => 'Stafford', 'Previous_BT' => 'Stafford'));
		Areacodes::create(array('area_code' => '01786', 'area_covered' => 'Stirling', 'official_Ofcom' => 'Stirling', 'Previous_BT' => 'Stirling'));
		Areacodes::create(array('area_code' => '01787', 'area_covered' => 'Sudbury', 'official_Ofcom' => 'Sudbury', 'Previous_BT' => 'Sudbury'));
		Areacodes::create(array('area_code' => '01788', 'area_covered' => 'Rugby', 'official_Ofcom' => 'Rugby', 'Previous_BT' => 'Rugby'));
		Areacodes::create(array('area_code' => '01789', 'area_covered' => 'Stratford-upon-Avon', 'official_Ofcom' => 'Stratford-upon-Avon', 'Previous_BT' => 'Stratford-upon-Avon'));
		Areacodes::create(array('area_code' => '01790', 'area_covered' => 'Spilsby', 'official_Ofcom' => 'Spilsby', 'Previous_BT' => 'Spilsby (see also 01507)'));
		Areacodes::create(array('area_code' => '01792', 'area_covered' => 'Swansea', 'official_Ofcom' => 'Swansea', 'Previous_BT' => 'Swansea'));
		Areacodes::create(array('area_code' => '01793', 'area_covered' => 'Swindon', 'official_Ofcom' => 'Swindon', 'Previous_BT' => 'Swindon'));
		Areacodes::create(array('area_code' => '01794', 'area_covered' => 'Romsey', 'official_Ofcom' => 'Romsey', 'Previous_BT' => 'Romsey'));
		Areacodes::create(array('area_code' => '01795', 'area_covered' => 'Sittingbourne', 'official_Ofcom' => 'Sittingbourne', 'Previous_BT' => 'Sittingbourne'));
		Areacodes::create(array('area_code' => '01796', 'area_covered' => 'Pitlochry', 'official_Ofcom' => 'Pitlochry', 'Previous_BT' => 'Pitlochry'));
		Areacodes::create(array('area_code' => '01797', 'area_covered' => 'Rye', 'official_Ofcom' => 'Rye', 'Previous_BT' => 'Rye'));
		Areacodes::create(array('area_code' => '01798', 'area_covered' => 'Pulborough', 'official_Ofcom' => 'Pulborough', 'Previous_BT' => 'Pulborough'));
		Areacodes::create(array('area_code' => '01799', 'area_covered' => 'Saffron Walden', 'official_Ofcom' => 'Saffron Walden', 'Previous_BT' => 'Saffron Walden'));
		Areacodes::create(array('area_code' => '01803', 'area_covered' => 'Torquay', 'official_Ofcom' => 'Torquay', 'Previous_BT' => 'Torquay'));
		Areacodes::create(array('area_code' => '01805', 'area_covered' => 'Torrington', 'official_Ofcom' => 'Torrington', 'Previous_BT' => 'Torrington'));
		Areacodes::create(array('area_code' => '01806', 'area_covered' => 'Sullom Voe, Shetland Islands', 'official_Ofcom' => 'Shetland', 'Previous_BT' => 'Voe'));
		Areacodes::create(array('area_code' => '01807', 'area_covered' => 'Ballindalloch', 'official_Ofcom' => 'Ballindalloch', 'Previous_BT' => 'Coupar Angus (see also 01828)'));
		Areacodes::create(array('area_code' => '01808', 'area_covered' => 'Tomatin', 'official_Ofcom' => 'Tomatin', 'Previous_BT' => 'Tomatin'));
		Areacodes::create(array('area_code' => '01809', 'area_covered' => 'Tomdoun', 'official_Ofcom' => 'Tomdoun', 'Previous_BT' => 'Tomdoun'));
		Areacodes::create(array('area_code' => '01821', 'area_covered' => 'Kinrossie', 'official_Ofcom' => 'Kinrossie', 'Previous_BT' => 'Kinrossie'));
		Areacodes::create(array('area_code' => '01822', 'area_covered' => 'Tavistock', 'official_Ofcom' => 'Tavistock', 'Previous_BT' => 'Tavistock'));
		Areacodes::create(array('area_code' => '01823', 'area_covered' => 'Taunton', 'official_Ofcom' => 'Taunton', 'Previous_BT' => 'Taunton'));
		Areacodes::create(array('area_code' => '01824', 'area_covered' => 'Ruthin', 'official_Ofcom' => 'Ruthin', 'Previous_BT' => 'Ruthin'));
		Areacodes::create(array('area_code' => '01825', 'area_covered' => 'Uckfield', 'official_Ofcom' => 'Uckfield', 'Previous_BT' => 'Uckfield'));
		Areacodes::create(array('area_code' => '01827', 'area_covered' => 'Tamworth', 'official_Ofcom' => 'Tamworth', 'Previous_BT' => 'Tamworth'));
		Areacodes::create(array('area_code' => '01828', 'area_covered' => 'Coupar Angus', 'official_Ofcom' => 'Coupar Angus', 'Previous_BT' => 'Coupar Angus (see also 01821)'));
		Areacodes::create(array('area_code' => '01829', 'area_covered' => 'Tarporley', 'official_Ofcom' => 'Tarporley', 'Previous_BT' => 'Tarporley'));
		Areacodes::create(array('area_code' => '01830', 'area_covered' => 'Kirkwhelpington', 'official_Ofcom' => 'Kirkwhelpington', 'Previous_BT' => 'Kirkwhelpington'));
		Areacodes::create(array('area_code' => '01832', 'area_covered' => 'Clopton', 'official_Ofcom' => 'Clopton', 'Previous_BT' => 'Clopton'));
		Areacodes::create(array('area_code' => '01833', 'area_covered' => 'Barnard Castle', 'official_Ofcom' => 'Barnard Castle', 'Previous_BT' => 'Barnard Castle'));
		Areacodes::create(array('area_code' => '01834', 'area_covered' => 'Narberth', 'official_Ofcom' => 'Narberth', 'Previous_BT' => 'Narberth'));
		Areacodes::create(array('area_code' => '01835', 'area_covered' => 'St Boswells', 'official_Ofcom' => 'St Boswells', 'Previous_BT' => 'St Boswells'));
		Areacodes::create(array('area_code' => '01837', 'area_covered' => 'Okehampton', 'official_Ofcom' => 'Okehampton', 'Previous_BT' => 'Okehampton'));
		Areacodes::create(array('area_code' => '01838', 'area_covered' => 'Dalmally', 'official_Ofcom' => 'Dalmally', 'Previous_BT' => 'Dalmally'));
		Areacodes::create(array('area_code' => '01840', 'area_covered' => 'Camelford', 'official_Ofcom' => 'Camelford', 'Previous_BT' => 'Camelford'));
		Areacodes::create(array('area_code' => '01841', 'area_covered' => 'Padstow', 'official_Ofcom' => 'Newquay', 'Previous_BT' => 'Newquay (see also 01637)'));
		Areacodes::create(array('area_code' => '01842', 'area_covered' => 'Thetford', 'official_Ofcom' => 'Thetford', 'Previous_BT' => 'Thetford'));
		Areacodes::create(array('area_code' => '01843', 'area_covered' => 'Thanet', 'official_Ofcom' => 'Thanet', 'Previous_BT' => 'Thanet'));
		Areacodes::create(array('area_code' => '01844', 'area_covered' => 'Thame', 'official_Ofcom' => 'Thame', 'Previous_BT' => 'Thame'));
		Areacodes::create(array('area_code' => '01845', 'area_covered' => 'Thirsk', 'official_Ofcom' => 'Thirsk', 'Previous_BT' => 'Thirsk'));
		Areacodes::create(array('area_code' => '01847', 'area_covered' => 'Thurso / Tongue', 'official_Ofcom' => 'Thurso / Tongue', 'Previous_BT' => 'Thurso / Tongue'));
		Areacodes::create(array('area_code' => '01848', 'area_covered' => 'Thornhill', 'official_Ofcom' => 'Thornhill', 'Previous_BT' => 'Thornhill'));
		Areacodes::create(array('area_code' => '01851', 'area_covered' => 'Lewis and Great Bernera, Outer Hebrides', 'official_Ofcom' => 'Great Bernera / Stornoway', 'Previous_BT' => 'Great Bernera / Stornoway'));
		Areacodes::create(array('area_code' => '01852', 'area_covered' => 'Kilmelford', 'official_Ofcom' => 'Kilmelford', 'Previous_BT' => 'Kilmelford'));
		Areacodes::create(array('area_code' => '01854', 'area_covered' => 'Ullapool', 'official_Ofcom' => 'Ullapool', 'Previous_BT' => 'Ullapool'));
		Areacodes::create(array('area_code' => '01855', 'area_covered' => 'Ballachulish', 'official_Ofcom' => 'Ballachulish', 'Previous_BT' => 'Ballachulish'));
		Areacodes::create(array('area_code' => '01856', 'area_covered' => 'Orkney', 'official_Ofcom' => 'Orkney', 'Previous_BT' => 'Kirkwall'));
		Areacodes::create(array('area_code' => '01857', 'area_covered' => 'Sanday', 'official_Ofcom' => 'Sanday', 'Previous_BT' => 'Sanday'));
		Areacodes::create(array('area_code' => '01858', 'area_covered' => 'Market Harborough', 'official_Ofcom' => 'Market Harborough', 'Previous_BT' => 'Market Harborough'));
		Areacodes::create(array('area_code' => '01859', 'area_covered' => 'Harris, Outer Hebrides', 'official_Ofcom' => 'Harris', 'Previous_BT' => 'Harris'));
		Areacodes::create(array('area_code' => '01862', 'area_covered' => 'Tain', 'official_Ofcom' => 'Tain', 'Previous_BT' => 'Tain'));
		Areacodes::create(array('area_code' => '01863', 'area_covered' => 'Ardgay', 'official_Ofcom' => 'Ardgay', 'Previous_BT' => 'Ardgay'));
		Areacodes::create(array('area_code' => '01864', 'area_covered' => 'Abington', 'official_Ofcom' => 'Abington', 'Previous_BT' => 'Abington'));
		Areacodes::create(array('area_code' => '01865', 'area_covered' => 'Oxford', 'official_Ofcom' => 'Oxford', 'Previous_BT' => 'Oxford'));
		Areacodes::create(array('area_code' => '01866', 'area_covered' => 'Kilchrenan', 'official_Ofcom' => 'Kilchrenan', 'Previous_BT' => 'Kilchrenan'));
		Areacodes::create(array('area_code' => '01869', 'area_covered' => 'Bicester', 'official_Ofcom' => 'Bicester', 'Previous_BT' => 'Bicester'));
		Areacodes::create(array('area_code' => '01870', 'area_covered' => 'Benebecula, Outer Hebrides', 'official_Ofcom' => 'Isle of Benbecula', 'Previous_BT' => 'Isle of Benbecula'));
		Areacodes::create(array('area_code' => '01871', 'area_covered' => 'Barra, Outer Hebrides', 'official_Ofcom' => 'Castlebay', 'Previous_BT' => 'Castlebay'));
		Areacodes::create(array('area_code' => '01872', 'area_covered' => 'Truro', 'official_Ofcom' => 'Truro', 'Previous_BT' => 'Truro'));
		Areacodes::create(array('area_code' => '01873', 'area_covered' => 'Abergavenny', 'official_Ofcom' => 'Abergavenny', 'Previous_BT' => 'Abergavenny'));
		Areacodes::create(array('area_code' => '01874', 'area_covered' => 'Brecon', 'official_Ofcom' => 'Brecon', 'Previous_BT' => 'Brecon'));
		Areacodes::create(array('area_code' => '01875', 'area_covered' => 'Tranent', 'official_Ofcom' => 'Tranent', 'Previous_BT' => 'Tranent'));
		Areacodes::create(array('area_code' => '01876', 'area_covered' => 'North Uist, Outer Hebrides', 'official_Ofcom' => 'Lochmaddy', 'Previous_BT' => 'Lochmaddy'));
		Areacodes::create(array('area_code' => '01877', 'area_covered' => 'Callander', 'official_Ofcom' => 'Callander', 'Previous_BT' => 'Trossachs'));
		Areacodes::create(array('area_code' => '01878', 'area_covered' => 'South Uist, Outer Hebrides', 'official_Ofcom' => 'Lochboisdale', 'Previous_BT' => 'Lochboisdale'));
		Areacodes::create(array('area_code' => '01879', 'area_covered' => 'Scarinish', 'official_Ofcom' => 'Scarinish', 'Previous_BT' => 'Scarinish'));
		Areacodes::create(array('area_code' => '01880', 'area_covered' => 'Tarbert', 'official_Ofcom' => 'Tarbert', 'Previous_BT' => 'Tarbert'));
		Areacodes::create(array('area_code' => '01882', 'area_covered' => 'Kinloch Rannoch', 'official_Ofcom' => 'Kinloch Rannoch', 'Previous_BT' => 'Kinloch Rannoch'));
		Areacodes::create(array('area_code' => '01883', 'area_covered' => 'Caterham', 'official_Ofcom' => 'Caterham', 'Previous_BT' => 'Merstham (see also 01737)'));
		Areacodes::create(array('area_code' => '01884', 'area_covered' => 'Tiverton', 'official_Ofcom' => 'Tiverton', 'Previous_BT' => 'Tiverton'));
		Areacodes::create(array('area_code' => '01885', 'area_covered' => 'Bromyard', 'official_Ofcom' => 'Pencombe', 'Previous_BT' => 'Bromyard (see also 01886)'));
		Areacodes::create(array('area_code' => '01886', 'area_covered' => 'Knightwick', 'official_Ofcom' => 'Bromyard', 'Previous_BT' => 'Bromyard (see also 01885)'));
		Areacodes::create(array('area_code' => '01887', 'area_covered' => 'Aberfeldy', 'official_Ofcom' => 'Aberfeldy', 'Previous_BT' => 'Aberfeldy'));
		Areacodes::create(array('area_code' => '01888', 'area_covered' => 'Turriff', 'official_Ofcom' => 'Turriff', 'Previous_BT' => 'Turriff'));
		Areacodes::create(array('area_code' => '01889', 'area_covered' => 'Rugeley', 'official_Ofcom' => 'Rugeley', 'Previous_BT' => 'Dapple Heath'));
		Areacodes::create(array('area_code' => '01890', 'area_covered' => 'Ayton / Coldstream', 'official_Ofcom' => 'Ayton / Coldstream', 'Previous_BT' => 'Ayton / Coldstream'));
		Areacodes::create(array('area_code' => '01892', 'area_covered' => 'Tunbridge Wells', 'official_Ofcom' => 'Tunbridge Wells', 'Previous_BT' => 'Tunbridge Wells'));
		Areacodes::create(array('area_code' => '01895', 'area_covered' => 'Uxbridge', 'official_Ofcom' => 'Uxbridge', 'Previous_BT' => 'Iver (see also 01753 and 01784)'));
		Areacodes::create(array('area_code' => '01896', 'area_covered' => 'Galashiels', 'official_Ofcom' => 'Galashiels', 'Previous_BT' => 'Galashiels'));
		Areacodes::create(array('area_code' => '01899', 'area_covered' => 'Biggar', 'official_Ofcom' => 'Biggar', 'Previous_BT' => 'Biggar'));
		Areacodes::create(array('area_code' => '01900', 'area_covered' => 'Workington', 'official_Ofcom' => 'Workington', 'Previous_BT' => 'Workington'));
		Areacodes::create(array('area_code' => '01902', 'area_covered' => 'Wolverhampton', 'official_Ofcom' => 'Wolverhampton', 'Previous_BT' => 'Wolverhampton (see also 01922)'));
		Areacodes::create(array('area_code' => '01903', 'area_covered' => 'Worthing', 'official_Ofcom' => 'Worthing', 'Previous_BT' => 'Worthing'));
		Areacodes::create(array('area_code' => '01904', 'area_covered' => 'York', 'official_Ofcom' => 'York', 'Previous_BT' => 'York'));
		Areacodes::create(array('area_code' => '01905', 'area_covered' => 'Worcester', 'official_Ofcom' => 'Worcester', 'Previous_BT' => 'Worcester'));
		Areacodes::create(array('area_code' => '01908', 'area_covered' => 'Milton Keynes', 'official_Ofcom' => 'Milton Keynes', 'Previous_BT' => 'Wolverton'));
		Areacodes::create(array('area_code' => '01909', 'area_covered' => 'Worksop', 'official_Ofcom' => 'Worksop', 'Previous_BT' => 'Worksop'));
		Areacodes::create(array('area_code' => '0191', 'area_covered' => 'Tyneside / Durham / Sunderland', 'official_Ofcom' => 'Tyneside / Durham / Sunderland', 'Previous_BT' => 'Tyneside / Wearside / Durham'));
		Areacodes::create(array('area_code' => '01920', 'area_covered' => 'Ware', 'official_Ofcom' => 'Ware', 'Previous_BT' => 'Knebworth (see also 01438)'));
		Areacodes::create(array('area_code' => '01922', 'area_covered' => 'Walsall', 'official_Ofcom' => 'Walsall', 'Previous_BT' => 'Wolverhampton (see also 01902)'));
		Areacodes::create(array('area_code' => '01923', 'area_covered' => 'Watford', 'official_Ofcom' => 'Watford', 'Previous_BT' => 'Watford'));
		Areacodes::create(array('area_code' => '01924', 'area_covered' => 'Wakefield', 'official_Ofcom' => 'Wakefield', 'Previous_BT' => 'Wakefield'));
		Areacodes::create(array('area_code' => '01925', 'area_covered' => 'Warrington', 'official_Ofcom' => 'Warrington', 'Previous_BT' => 'Warrington'));
		Areacodes::create(array('area_code' => '01926', 'area_covered' => 'Warwick', 'official_Ofcom' => 'Warwick', 'Previous_BT' => 'Leamington Spa'));
		Areacodes::create(array('area_code' => '01928', 'area_covered' => 'Runcorn', 'official_Ofcom' => 'Runcorn', 'Previous_BT' => 'Frodsham'));
		Areacodes::create(array('area_code' => '01929', 'area_covered' => 'Wareham', 'official_Ofcom' => 'Wareham', 'Previous_BT' => 'Wareham'));
		Areacodes::create(array('area_code' => '01931', 'area_covered' => 'Shap', 'official_Ofcom' => 'Shap', 'Previous_BT' => 'Shap'));
		Areacodes::create(array('area_code' => '01932', 'area_covered' => 'Weybridge', 'official_Ofcom' => 'Weybridge', 'Previous_BT' => 'Esher (see also 01372)'));
		Areacodes::create(array('area_code' => '01933', 'area_covered' => 'Wellingborough', 'official_Ofcom' => 'Wellingborough', 'Previous_BT' => 'Wellingborough'));
		Areacodes::create(array('area_code' => '01934', 'area_covered' => 'Weston-Super-Mare', 'official_Ofcom' => 'Weston-Super-Mare', 'Previous_BT' => 'Weston-Super-Mare'));
		Areacodes::create(array('area_code' => '01935', 'area_covered' => 'Yeovil', 'official_Ofcom' => 'Yeovil', 'Previous_BT' => 'Yeovil'));
		Areacodes::create(array('area_code' => '01937', 'area_covered' => 'Wetherby', 'official_Ofcom' => 'Wetherby', 'Previous_BT' => 'Wetherby'));
		Areacodes::create(array('area_code' => '01938', 'area_covered' => 'Welshpool', 'official_Ofcom' => 'Welshpool', 'Previous_BT' => 'Welshpool'));
		Areacodes::create(array('area_code' => '01939', 'area_covered' => 'Wem', 'official_Ofcom' => 'Wem', 'Previous_BT' => 'Wem'));
		Areacodes::create(array('area_code' => '01942', 'area_covered' => 'Wigan', 'official_Ofcom' => 'Wigan', 'Previous_BT' => 'Wigan'));
		Areacodes::create(array('area_code' => '01943', 'area_covered' => 'Guiseley', 'official_Ofcom' => 'Guiseley', 'Previous_BT' => 'Guiseley'));
		Areacodes::create(array('area_code' => '01944', 'area_covered' => 'West Heslerton', 'official_Ofcom' => 'West Heslerton', 'Previous_BT' => 'West Heslerton'));
		Areacodes::create(array('area_code' => '01945', 'area_covered' => 'Wisbech', 'official_Ofcom' => 'Wisbech', 'Previous_BT' => 'Wisbech'));
		Areacodes::create(array('area_code' => '01946', 'area_covered' => 'Whitehaven', 'official_Ofcom' => 'Whitehaven', 'Previous_BT' => 'Whitehaven'));
		Areacodes::create(array('area_code' => '019467', 'area_covered' => 'Gosforth', 'official_Ofcom' => 'Gosforth', 'Previous_BT' => 'Gosforth'));
		Areacodes::create(array('area_code' => '01947', 'area_covered' => 'Whitby', 'official_Ofcom' => 'Whitby', 'Previous_BT' => 'Whitby'));
		Areacodes::create(array('area_code' => '01948', 'area_covered' => 'Whitchurch', 'official_Ofcom' => 'Whitchurch', 'Previous_BT' => 'Whitchurch'));
		Areacodes::create(array('area_code' => '01949', 'area_covered' => 'Whatton', 'official_Ofcom' => 'Whatton', 'Previous_BT' => 'Whatton'));
		Areacodes::create(array('area_code' => '01950', 'area_covered' => 'Sandwick, Shetland Islands', 'official_Ofcom' => 'Sandwick', 'Previous_BT' => 'Sandwick'));
		Areacodes::create(array('area_code' => '01951', 'area_covered' => 'Colonsay', 'official_Ofcom' => 'Colonsay', 'Previous_BT' => 'Colonsay'));
		Areacodes::create(array('area_code' => '01952', 'area_covered' => 'Telford', 'official_Ofcom' => 'Telford', 'Previous_BT' => 'Wellington'));
		Areacodes::create(array('area_code' => '01953', 'area_covered' => 'Wymondham', 'official_Ofcom' => 'Wymondham', 'Previous_BT' => 'Attleborough'));
		Areacodes::create(array('area_code' => '01954', 'area_covered' => 'Madingley', 'official_Ofcom' => 'Madingley', 'Previous_BT' => 'Madingley'));
		Areacodes::create(array('area_code' => '01955', 'area_covered' => 'Wick', 'official_Ofcom' => 'Wick', 'Previous_BT' => 'Wick'));
		Areacodes::create(array('area_code' => '01957', 'area_covered' => 'Mid Yell, Shetland Islands', 'official_Ofcom' => 'Mid Yell', 'Previous_BT' => 'Mid Yell'));
		Areacodes::create(array('area_code' => '01959', 'area_covered' => 'Westerham', 'official_Ofcom' => 'Westerham', 'Previous_BT' => 'Swanley (see also 01322 and 01689)'));
		Areacodes::create(array('area_code' => '01962', 'area_covered' => 'Winchester', 'official_Ofcom' => 'Winchester', 'Previous_BT' => 'Winchester'));
		Areacodes::create(array('area_code' => '01963', 'area_covered' => 'Wincanton', 'official_Ofcom' => 'Wincanton', 'Previous_BT' => 'Templecombe'));
		Areacodes::create(array('area_code' => '01964', 'area_covered' => 'Hornsea / Patrington', 'official_Ofcom' => 'Hornsea / Patrington', 'Previous_BT' => 'Hornsea / Patrington'));
		Areacodes::create(array('area_code' => '01967', 'area_covered' => 'Strontian', 'official_Ofcom' => 'Strontian', 'Previous_BT' => 'Strontian'));
		Areacodes::create(array('area_code' => '01968', 'area_covered' => 'Penicuik', 'official_Ofcom' => 'Penicuik', 'Previous_BT' => 'Penicuik'));
		Areacodes::create(array('area_code' => '01969', 'area_covered' => 'Leyburn', 'official_Ofcom' => 'Leyburn', 'Previous_BT' => 'Leyburn'));
		Areacodes::create(array('area_code' => '01970', 'area_covered' => 'Aberystwyth', 'official_Ofcom' => 'Aberystwyth', 'Previous_BT' => 'Aberystwyth'));
		Areacodes::create(array('area_code' => '01971', 'area_covered' => 'Scourie', 'official_Ofcom' => 'Scourie', 'Previous_BT' => 'Scourie'));
		Areacodes::create(array('area_code' => '01972', 'area_covered' => 'Glenborrodale', 'official_Ofcom' => 'Glenborrodale', 'Previous_BT' => 'Glenborrodale'));
		Areacodes::create(array('area_code' => '01974', 'area_covered' => 'Llanon', 'official_Ofcom' => 'Llanon', 'Previous_BT' => 'Llanon'));
		Areacodes::create(array('area_code' => '01975', 'area_covered' => 'Alford (Aberdeen) / Strathdon', 'official_Ofcom' => 'Alford (Aberdeen) / Strathdon', 'Previous_BT' => 'Alford (Aberdeen) / Strathdon'));
		Areacodes::create(array('area_code' => '01977', 'area_covered' => 'Pontefract', 'official_Ofcom' => 'Pontefract', 'Previous_BT' => 'Pontefract'));
		Areacodes::create(array('area_code' => '01978', 'area_covered' => 'Wrexham', 'official_Ofcom' => 'Wrexham', 'Previous_BT' => 'Wrexham'));
		Areacodes::create(array('area_code' => '01980', 'area_covered' => 'Amesbury', 'official_Ofcom' => 'Amesbury', 'Previous_BT' => 'Bulford Camp'));
		Areacodes::create(array('area_code' => '01981', 'area_covered' => 'Wormbridge', 'official_Ofcom' => 'Wormbridge', 'Previous_BT' => 'Wormbridge'));
		Areacodes::create(array('area_code' => '01982', 'area_covered' => 'Builth Wells', 'official_Ofcom' => 'Builth Wells', 'Previous_BT' => 'Builth Wells'));
		Areacodes::create(array('area_code' => '01983', 'area_covered' => 'Isle of Wight', 'official_Ofcom' => 'Isle of Wight', 'Previous_BT' => 'Ryde'));
		Areacodes::create(array('area_code' => '01984', 'area_covered' => 'Watchet', 'official_Ofcom' => 'Watchet', 'Previous_BT' => 'Stogumber'));
		Areacodes::create(array('area_code' => '01985', 'area_covered' => 'Warminster', 'official_Ofcom' => 'Warminster', 'Previous_BT' => 'Warminster'));
		Areacodes::create(array('area_code' => '01986', 'area_covered' => 'Bungay', 'official_Ofcom' => 'Bungay', 'Previous_BT' => 'Bungay'));
		Areacodes::create(array('area_code' => '01987', 'area_covered' => 'Ebbsfleet', 'official_Ofcom' => 'Ebbsfleet', 'Previous_BT' => 'n/a (new code introduced in 2008)'));
		Areacodes::create(array('area_code' => '01988', 'area_covered' => 'Wigtown', 'official_Ofcom' => 'Wigtown', 'Previous_BT' => 'Wigtown'));
		Areacodes::create(array('area_code' => '01989', 'area_covered' => 'Ross-on-Wye', 'official_Ofcom' => 'Ross-on-Wye', 'Previous_BT' => 'Ross-on-Wye'));
		Areacodes::create(array('area_code' => '01992', 'area_covered' => 'Lea Valley', 'official_Ofcom' => 'Lea Valley', 'Previous_BT' => 'Hoddesdon'));
		Areacodes::create(array('area_code' => '01993', 'area_covered' => 'Witney', 'official_Ofcom' => 'Witney', 'Previous_BT' => 'Witney'));
		Areacodes::create(array('area_code' => '01994', 'area_covered' => 'St Clears', 'official_Ofcom' => 'St Clears', 'Previous_BT' => 'St Clears'));
		Areacodes::create(array('area_code' => '01995', 'area_covered' => 'Garstang', 'official_Ofcom' => 'Garstang', 'Previous_BT' => 'Garstang'));
		Areacodes::create(array('area_code' => '01997', 'area_covered' => 'Strathpeffer', 'official_Ofcom' => 'Strathpeffer', 'Previous_BT' => 'Strathpeffer'));
		Areacodes::create(array('area_code' => '020', 'area_covered' => 'London', 'official_Ofcom' => 'London', 'Previous_BT' => 'London'));
		Areacodes::create(array('area_code' => '023', 'area_covered' => 'Southampton / Portsmouth', 'official_Ofcom' => 'Southampton / Portsmouth', 'Previous_BT' => 'Southampton / Portsmouth'));
		Areacodes::create(array('area_code' => '024', 'area_covered' => 'Coventry', 'official_Ofcom' => 'Coventry', 'Previous_BT' => 'Coventry'));
		Areacodes::create(array('area_code' => '028', 'area_covered' => 'Northern Ireland', 'official_Ofcom' => 'Northern Ireland', 'Previous_BT' => 'Northern Ireland'));
		Areacodes::create(array('area_code' => '029', 'area_covered' => 'Cardiff', 'official_Ofcom' => 'Cardiff', 'Previous_BT' => 'Cardiff'));


	}

}