<?php


class SubcategoriesTableSeeder extends Seeder {

	public function run()
	{

		DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('subcategory_categories')->truncate();
        DB::table('subcategories')->truncate();
		DB::statement('SET FOREIGN_KEY_CHECKS = 1');
        
Subcategory::create(array('name' => '​dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'belly dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'belly dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'body jam', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'bokwa', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'ballet', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'ballroom', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'bollywood', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'freestyle', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'hip hop', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'hula', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'charleston', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'breakdancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'breakdance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'lindy hop', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'jive', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'salsa', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'street', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'urban funk', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'line dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'zumba step', 'description' => 'awaiting details'))->categories()->attach([1,3]);
Subcategory::create(array('name' => '​puma hit', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'v tread', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'v row', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'zuu', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'v core', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'power plate', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => '​beaming', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'body conditioning', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'body pump', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'bootcamp', 'description' => 'awaiting details'))->categories()->attach([7]);
Subcategory::create(array('name' => 'burn 360', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'cxworx', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'kinesis', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'vipr 3d', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'fighting', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'martial arts', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'mixed martial arts', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'mma', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'ufc', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'ultimate fighting', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'capoeiera', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'karate', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'kung fu', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'wing chun', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'tai chi', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'aikido', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'taekwondo', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'combat', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'jujitsu', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => '​body combat', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'kickboxing', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'boxing', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'skipping', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'tae kwon do', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'thai kickboxing', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'muay thai', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'wu shu kwan', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'cycling', 'description' => 'awaiting details'))->categories()->attach([3,9,6]);
Subcategory::create(array('name' => '​spin', 'description' => 'awaiting details'))->categories()->attach([3,9,6]);
Subcategory::create(array('name' => 'group cycle', 'description' => 'awaiting details'))->categories()->attach([3,9,6]);
Subcategory::create(array('name' => 'rpm', 'description' => 'awaiting details'))->categories()->attach([3,9,6]);
Subcategory::create(array('name' => 'spinning', 'description' => 'awaiting details'))->categories()->attach([3,9,6]);
Subcategory::create(array('name' => '​aqua', 'description' => 'awaiting details'))->categories()->attach([10,6]);
Subcategory::create(array('name' => 'aqua zumba', 'description' => 'awaiting details'))->categories()->attach([10,1]);
Subcategory::create(array('name' => '​aerobics', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'aerobic', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'body attack', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'body step', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'body vive', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'cardio mix', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'step', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'willpower and grace', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'sports', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'sport', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => '​tennis', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'badminton', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'swimming', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'squash', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'personal training', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'personal trainer', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'pt', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => '​pilates', 'description' => 'awaiting details'))->categories()->attach([2]);
Subcategory::create(array('name' => 'yoga', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'hot yoga', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'bikram yoga', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'pre natal', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'post natal', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'prenatal', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'postnatal', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'ashtanga yoga', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'body', 'description' => 'awaiting details'))->categories()->attach([5,3]);
Subcategory::create(array('name' => 'body balance​', 'description' => 'awaiting details'))->categories()->attach([5,3]);
Subcategory::create(array('name' => 'workout', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'work out', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'gyms', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'gym', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'acro dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'bachata dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'ballet dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'ballroom dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'circle dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'contemporary dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'country western dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'cumbia dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'disco dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'erotic dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'hip hop dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'hula dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'jazz dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'jive dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'lap dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'modern dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'pole dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'salsa dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'scottish highland dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'street dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'swing dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'tango dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'tap dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'waltz dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'bachata dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'ballet dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'ballroom dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'circle dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'contemporary dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'country western dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'cumbia dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'disco dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'erotic dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'folk dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'georgian dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'hip hop dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'hula dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'jazz dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'jive dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'lap dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'line dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'modern dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'pole dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'persian dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'salsa dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'scottish highland dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'street dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'swing dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'tango dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'tap dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'waltz dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'brazilian jiu jitsu', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'capoeira', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'judo', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'kendo', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'sumo', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'silat', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'kali', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'muay thai', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'silat pattani', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'amateur wrestling', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'chess boxing', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'fencing', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'sambo', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'kung fu toa', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'volleyball', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'basketball', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'netball', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'dodgeball', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'rock climbing', 'description' => 'awaiting details'))->categories()->attach([3,6]);
Subcategory::create(array('name' => 'abseiling', 'description' => 'awaiting details'))->categories()->attach([3,6]);
Subcategory::create(array('name' => 'rope climbing', 'description' => 'awaiting details'))->categories()->attach([3,6]);
Subcategory::create(array('name' => 'jujutsu', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'wrestling', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'chessboxing', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'fujian white crane', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'kenpo', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'shaolin kung fu', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'taido', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'wing tsun', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'ninjutsu', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'wushu', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'australian football', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'trampolining', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'ice hockey', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'aerobic gymnastics', 'description' => 'awaiting details'))->categories()->attach([6,8]);
Subcategory::create(array('name' => 'table tennis', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'hockey', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'cheerleading', 'description' => 'awaiting details'))->categories()->attach([6,8,1]);
Subcategory::create(array('name' => 'running', 'description' => 'awaiting details'))->categories()->attach([3,6]);
Subcategory::create(array('name' => 'rowing', 'description' => 'awaiting details'))->categories()->attach([3,6]);
Subcategory::create(array('name' => 'ice skating', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'figure skating', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'military bootcamp', 'description' => 'awaiting details'))->categories()->attach([3,7]);
Subcategory::create(array('name' => 'military bootcamps', 'description' => 'awaiting details'))->categories()->attach([3,7]);
Subcategory::create(array('name' => 'military boot camp', 'description' => 'awaiting details'))->categories()->attach([3,7]);
Subcategory::create(array('name' => 'military boot camps', 'description' => 'awaiting details'))->categories()->attach([3,7]);
Subcategory::create(array('name' => 'bootcamp', 'description' => 'awaiting details'))->categories()->attach([3,7]);
Subcategory::create(array('name' => 'bootcamps', 'description' => 'awaiting details'))->categories()->attach([3,7]);
Subcategory::create(array('name' => 'boot camp', 'description' => 'awaiting details'))->categories()->attach([3,7]);
Subcategory::create(array('name' => 'boot camps', 'description' => 'awaiting details'))->categories()->attach([3,7]);
Subcategory::create(array('name' => 'fitness bootcamp', 'description' => 'awaiting details'))->categories()->attach([3,7]);
Subcategory::create(array('name' => 'fitness bootcamps', 'description' => 'awaiting details'))->categories()->attach([3,7]);
Subcategory::create(array('name' => 'fitness boot camp', 'description' => 'awaiting details'))->categories()->attach([3,7]);
Subcategory::create(array('name' => 'fitness boot camps', 'description' => 'awaiting details'))->categories()->attach([3,7]);
Subcategory::create(array('name' => '', 'description' => 'awaiting details'))->categories()->attach([]);
Subcategory::create(array('name' => '', 'description' => 'awaiting details'))->categories()->attach([]);
Subcategory::create(array('name' => 'zumba', 'description' => 'awaiting details'))->categories()->attach([3,1]);
Subcategory::create(array('name' => 'circuits', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'aqua aerobic', 'description' => 'awaiting details'))->categories()->attach([8]);
Subcategory::create(array('name' => 'water aerobic', 'description' => 'awaiting details'))->categories()->attach([8]);
Subcategory::create(array('name' => 'water aerobics', 'description' => 'awaiting details'))->categories()->attach([8]);
Subcategory::create(array('name' => 'zumba tonic', 'description' => 'awaiting details'))->categories()->attach([3,1]);
Subcategory::create(array('name' => 'zumba sentao ', 'description' => 'awaiting details'))->categories()->attach([3,1]);
Subcategory::create(array('name' => 'zumba gold ', 'description' => 'awaiting details'))->categories()->attach([3,1]);
Subcategory::create(array('name' => 'zumbini', 'description' => 'awaiting details'))->categories()->attach([3,1]);
Subcategory::create(array('name' => 'zumba in the circuit', 'description' => 'awaiting details'))->categories()->attach([3,1]);
Subcategory::create(array('name' => 'zumba gold toning', 'description' => 'awaiting details'))->categories()->attach([3,1]);
Subcategory::create(array('name' => '20 20 20', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Cardio ', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Abs Attack ', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Core condition', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Booiaka', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'Walking ', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'X-training ', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Sandbell', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Kettlebell', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Sandbell ', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Swiss ball ', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Stretch & abs', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Boxercise', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'Step', 'description' => 'awaiting details'))->categories()->attach([3,8]);
Subcategory::create(array('name' => 'Body Strengh', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Aerial discipline', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Sculpt', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Aqua fit', 'description' => 'awaiting details'))->categories()->attach([10]);
Subcategory::create(array('name' => 'Ballroom dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'Circuit training ', 'description' => 'awaiting details'))->categories()->attach([]);
Subcategory::create(array('name' => 'BarreConcept', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'Beam Fit', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Buggy bootcamp', 'description' => 'awaiting details'))->categories()->attach([7]);
Subcategory::create(array('name' => 'Buggy fitness', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Kizomba', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'flamenco', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'Zouk', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'Dancehall', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'Ragga', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'Gymnastic', 'description' => 'awaiting details'))->categories()->attach([3,6]);
Subcategory::create(array('name' => 'Jazzercise', 'description' => 'awaiting details'))->categories()->attach([3,1]);
Subcategory::create(array('name' => 'Kettlercise', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Pre/Post natal Yoga', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'Khai bo', 'description' => 'awaiting details'))->categories()->attach([4]);
Subcategory::create(array('name' => 'Salsa aerobics', 'description' => 'awaiting details'))->categories()->attach([8,1,3]);
Subcategory::create(array('name' => 'Konga', 'description' => 'awaiting details'))->categories()->attach([3,1]);
Subcategory::create(array('name' => 'Legs, Bums, Tums', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Power Plate', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Swimming', 'description' => 'awaiting details'))->categories()->attach([3,6]);
Subcategory::create(array('name' => 'Power Walking', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Abs & back', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Powerbags', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Horse ball', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'Powerhoop', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'Waterpolo', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'Pre/Post natal Pilates', 'description' => 'awaiting details'))->categories()->attach([2]);

	}


}