<?php


class SubcategoriesTableSeeder extends Seeder {

	public function run()
	{

		DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('subcategory_categories')->truncate();
        DB::table('subcategories')->truncate();
		DB::statement('SET FOREIGN_KEY_CHECKS = 1');
      
Subcategory::create(array('name' => '​dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'belly dancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'body jam', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'bokwa', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'ballet', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'ballroom', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'bollywood', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'freestyle', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'hip hop', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'hula', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'charleston', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'breakdancing', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'salsa', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'street dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'urban funk', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'line dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'Puma HIIT ', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'v tread', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'v row', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'zuu', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'power plate', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => '​beaming', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'body conditioning', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'body pump', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'bootcamp', 'description' => 'awaiting details'))->categories()->attach([7]);
Subcategory::create(array('name' => 'kinesiology', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'vipr ', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'fighting', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'martial arts', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'mixed martial arts', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'capoeiera', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'karate', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'kung fu', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'wing chun', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'tai chi', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'aikido', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'taekwondo', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'combat', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'jujitsu', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => '​body combat', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'kickboxing', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'boxing', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'skipping', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'thai kickboxing', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'wu shu kwan', 'description' => 'awaiting details'))->categories()->attach([3,4,6]);
Subcategory::create(array('name' => 'cycling', 'description' => 'awaiting details'))->categories()->attach([3,9,6]);
Subcategory::create(array('name' => 'group cycle', 'description' => 'awaiting details'))->categories()->attach([3,9,6]);
Subcategory::create(array('name' => 'rpm', 'description' => 'awaiting details'))->categories()->attach([3,9,6]);
Subcategory::create(array('name' => 'spinning', 'description' => 'awaiting details'))->categories()->attach([3,9,6]);
Subcategory::create(array('name' => '​aqua', 'description' => 'awaiting details'))->categories()->attach([10,6]);
Subcategory::create(array('name' => '​aerobics', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'body attack', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'body step', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'body vive', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'cardio mix', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'willpower and grace', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'sports', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => '​tennis', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'badminton', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'swimming', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'squash', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'personal training', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => '​pilates', 'description' => 'awaiting details'))->categories()->attach([2]);
Subcategory::create(array('name' => 'yoga', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'hot yoga', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'Yoga Iyengar', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'yoga kundalini', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'hatha yoga', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'yoga vinyasa', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'ashtanga yoga', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'body balance​', 'description' => 'awaiting details'))->categories()->attach([5,3]);
Subcategory::create(array('name' => 'workout', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'acro dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'bachata dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'contemporary dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'jazz dance', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'brazilian jiu jitsu', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'judo', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'kendo', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'muay thai', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'chess boxing', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'fencing', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'sambo', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'volleyball', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'basketball', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'netball', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'dodgeball', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'rock climbing', 'description' => 'awaiting details'))->categories()->attach([3,6]);
Subcategory::create(array('name' => 'rope climbing', 'description' => 'awaiting details'))->categories()->attach([3,6]);
Subcategory::create(array('name' => 'australian football', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'trampolining', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'ice hockey', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'table tennis', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'hockey', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'cheerleading', 'description' => 'awaiting details'))->categories()->attach([6,8,1]);
Subcategory::create(array('name' => 'running', 'description' => 'awaiting details'))->categories()->attach([3,6]);
Subcategory::create(array('name' => 'rowing', 'description' => 'awaiting details'))->categories()->attach([3,6]);
Subcategory::create(array('name' => 'ice skating', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'figure skating', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'zumba', 'description' => 'awaiting details'))->categories()->attach([3,1]);
Subcategory::create(array('name' => 'circuits', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => '20 20 20', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Abs Attack ', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Booiaka', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'Kettlebell', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Stretch and abs', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Boxercise', 'description' => 'awaiting details'))->categories()->attach([3,4]);
Subcategory::create(array('name' => 'Step', 'description' => 'awaiting details'))->categories()->attach([3,8]);
Subcategory::create(array('name' => 'Sculpt', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'BarreConcept', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'Buggy bootcamp', 'description' => 'awaiting details'))->categories()->attach([7]);
Subcategory::create(array('name' => 'Kizomba', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'flamenco', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'Zouk', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'Ragga Dancehall', 'description' => 'awaiting details'))->categories()->attach([1]);
Subcategory::create(array('name' => 'Gymnastics', 'description' => 'awaiting details'))->categories()->attach([3,6]);
Subcategory::create(array('name' => 'Jazzercise', 'description' => 'awaiting details'))->categories()->attach([3,1]);
Subcategory::create(array('name' => 'Kettlercise', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Pre/Post natal Yoga', 'description' => 'awaiting details'))->categories()->attach([5]);
Subcategory::create(array('name' => 'Legs, Bums, Tums', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Powerbags', 'description' => 'awaiting details'))->categories()->attach([3]);
Subcategory::create(array('name' => 'Horse ball', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'Powerhoop', 'description' => 'awaiting details'))->categories()->attach([8,3]);
Subcategory::create(array('name' => 'Waterpolo', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'Pre/Post natal Pilates', 'description' => 'awaiting details'))->categories()->attach([2]);
Subcategory::create(array('name' => 'Football', 'description' => 'awaiting details'))->categories()->attach([6]);
Subcategory::create(array('name' => 'Nutrition', 'description' => 'awaiting details'))->categories()->attach([11]);
	}


}